Add minValue, maxValue & validation in number widget
the-deep/client pull request #101
Opened 2018-07-16 06:16 UTC by AdityaKhatri

2018-07-16 08:48 UTC, tnagorra approved these changes

2018-07-20 07:27 UTC, frozenhelium requested changes

2018-07-20 07:27 UTC, frozenhelium commented on src/redux/initial-state/dev-lang.js
> +        1002: 'Min Value',
Improper casing
Max Value -> Max value

2018-07-20 07:27 UTC, frozenhelium commented on src/widgets/NumberWidget/Framework/ListWidget.js
> +            {
Prefer destructuring

2018-07-23 06:47 UTC, merged