Feature/analysis stats viz
the-deep/client pull request #1423
Opened 2021-03-15 11:24 UTC by subinasr

2021-03-17 04:01 UTC, AdityaKhatri commented on src/views/AnalysisModule/index.tsx
> +const colorScheme = [
Use colorBrewer. Refer to colorInput.
https://github.com/saikocat/colorbrewer

2021-03-17 04:03 UTC, AdityaKhatri requested changes
Waiting for fixes

2021-03-17 08:42 UTC, tnagorra commented on src/components/viz/Timeline/index.tsx
> +        data.sort((a, b) => (valueSelector(a) - valueSelector(b)))
```suggestion
        [...data].sort((a, b) => (valueSelector(a) - valueSelector(b)))
```

2021-03-17 08:43 UTC, tnagorra commented on src/components/viz/Timeline/index.tsx
> +        data.sort((a, b) => (valueSelector(a) - valueSelector(b)))
Please use compareNumber(valueSelector(a), valueSelector(b))

2021-03-17 08:43 UTC, tnagorra commented on src/typings/analysisModule.tsx
> +export interface PillarAnalysisElement extends AnalysisPillars{
```suggestion
export interface PillarAnalysisElement extends AnalysisPillars {
```

2021-03-17 08:44 UTC, tnagorra commented on src/typings/analysisModule.tsx
> +export interface PillarAnalysisElement extends AnalysisPillars{
Please move this after AnalysisPillars

2021-03-17 08:46 UTC, tnagorra commented on src/views/AnalysisModule/index.tsx
> +    const timelineData: TimelineData = (analysisResponse?.results ?? []).map(d => ({
```suggestion
    const timelineData: TimelineData = (analysisResponse?.results?.map(d => ({
```

2021-03-17 08:46 UTC, tnagorra commented on src/views/AnalysisModule/index.tsx
> +                                {piechartData.map((_: any, index: number) => (
```suggestion
                                {piechartData.map((_: unknown, index: number) => (
```

2021-03-17 08:48 UTC, tnagorra commented on src/views/AnalysisModule/index.tsx
> +                                        key={keySelector}
```suggestion
                                        key={_.organizationId}
```

2021-03-17 08:49 UTC, tnagorra commented on src/views/AnalysisModule/index.tsx
> +                        data={timelineData ?? []}
```suggestion
                        data={timelineData}
```

2021-03-17 08:49 UTC, tnagorra commented on src/views/AnalysisModule/styles.scss
> +
```suggestion
```

2021-03-17 09:20 UTC, samshara commented on src/views/AnalysisModule/index.tsx
> +import colorBrewer from 'colorbrewer';
instead of this library we could use d3-scale-chromatic which includes color scheme from colorbrewer.

2021-03-17 09:20 UTC, samshara commented on src/views/AnalysisModule/index.tsx
> +    const piechartData: AuthoringOrganizations = overviewResponse?.authoringOrganizations ?? [];
shouldn't it be as overviewResponse?.results.authoringOrganizations ?. If not then you should remove <MultiResponse<T>> type from the corresponding useRequest. The type for pieChartData should be AuthoringOrganizations[].

2021-03-17 09:20 UTC, samshara commented on src/views/AnalysisModule/index.tsx
> +    const timelineData: TimelineData = (analysisResponse?.results ?? []).map(d => ({
```suggestion
    const timelineData: TimelineData[]= (analysisResponse?.results ?? []).map(d => ({
```

2021-03-17 09:20 UTC, samshara commented on src/views/AnalysisModule/index.tsx
> +        value: new Date(d.createdAt).getTime(),
Here value is of type Number but it is defined to be a string in the TimelineData interface. Similarly, createdAt is optional in AnalysisElement type and it should be handled properly.

2021-03-17 09:20 UTC, samshara commented on src/views/AnalysisModule/index.tsx
> +        value: new Date(d.createdAt).getTime(),
Here value is of type Number but it is defined to be a string in the TimelineData interface. Similarly, createdAt is optional in AnalysisElement type and it should be handled properly.

2021-03-17 09:20 UTC, samshara commented on src/views/AnalysisModule/index.tsx
> +                                        fill={colorScheme[index % colorScheme.length]}
```suggestion
                                {piechartData.map((value: AuthoringOrganizations, index: number) => (
                                    <Cell
                                        key={value.organizationId}
                                        fill={colorScheme[index % colorScheme.length]}
```

2021-03-17 09:20 UTC, samshara commented on src/views/AnalysisModule/index.tsx
> +                        valueSelector={timelineValueSelector}
here Timeline component expects valueSelector to return number. It is always a good idea to maintain type safety.

2021-03-17 09:58 UTC, subinasr commented on src/views/AnalysisModule/index.tsx
> +import colorBrewer from 'colorbrewer';
We've already used this in ColorInput so I think its fine for now.

2021-03-17 10:20 UTC, tnagorra commented on src/views/AnalysisModule/Analysis/AnalysisPillar/index.tsx
> +    createdAt: string | number;
```suggestion
    createdAt: string;
```

2021-03-18 09:18 UTC, samshara approved these changes

2021-03-19 06:09 UTC, merged