Setup PillarAnalysis page
the-deep/client pull request #1425
Opened 2021-03-16 07:53 UTC by AdityaKhatri

2021-03-16 07:56 UTC, subinasr commented on src/components/general/FullPageHeader/index.tsx
> +import _ts from '#ts';
If ts is not used, maybe it's better to remove this.

2021-03-16 08:30 UTC, subinasr commented on src/views/PillarAnalysis/index.tsx
> +import { _cs } from '@togglecorp/fujs';
_cs is not used.

2021-03-16 08:31 UTC, subinasr approved these changes

2021-03-16 12:18 UTC, frozenhelium requested changes

2021-03-16 12:18 UTC, frozenhelium commented on src/components/general/FullPageHeader/index.tsx
> +            </div>
We have `ElementsFragment` component for this layout
```jsx
<div className={_cs(styles.fullPageHeader, className)}>
    <ElementsFragment
        icons={...}
        actions={...}
    >
        {children}
    </ElementsFragment>
</div>
```

2021-03-16 12:18 UTC, frozenhelium commented on src/components/ui/BackLink/index.tsx
> +    const goBack = useCallback((e) => {
use consistent function naming
Suggestion: `handleClick` or `handleLinkClick`

2021-03-16 12:18 UTC, frozenhelium commented on src/constants/styleProperties.js
> +        duiHeightNavbarIcon: '48px',
use relative unit (`rem`)

2021-03-17 09:07 UTC, tnagorra commented on src/views/PillarAnalysis/index.tsx
> +    const [value, setValue] = useState<string | undefined>('');
```suggestion
    const [value, setValue] = useState<string | undefined>();
```

2021-03-17 09:26 UTC, tnagorra approved these changes

2021-03-17 09:56 UTC, merged