Feature/new project flow project details
the-deep/client pull request #1474
Opened 2021-03-24 11:30 UTC by samshara

depends on https://github.com/the-deep/server/pull/698

2021-03-25 03:58 UTC, tnagorra commented on src/views/ProjectEdit/styles.scss
> +    background-color: white;
Please use css variables for color

2021-03-25 03:58 UTC, tnagorra commented on src/views/ProjectEdit/ProjectDetailsForm/styles.scss
> +                background-color: white;
Please use css-variable for color

2021-03-25 03:58 UTC, tnagorra commented on src/views/ProjectEdit/ProjectDetailsForm/styles.scss
> +                    background-color: white;
Please use css-variable for color

2021-03-25 04:01 UTC, tnagorra commented on src/components/general/OrganizationList/index.tsx
> +            heading={fieldsMap[data[0].organizationType]}
Why are we only using organizationType for first datum.
Also, we can just use a find instead of creating a mapping here.

2021-03-25 04:02 UTC, tnagorra commented on src/components/general/AddStakeholdersModal/OrganizationField/index.tsx
> +            if (!parsedData || !parsedData.organizationId) {
Good Catch!

2021-03-25 04:03 UTC, tnagorra commented on src/views/ProjectEdit/ProjectDetailsForm/index.tsx
> +    };
We should move this outside the component

2021-03-25 04:04 UTC, tnagorra commented on src/views/ProjectEdit/ProjectDetailsForm/index.tsx
> +        );
This should be ouside the renderParams function and memoized as well.

2021-03-25 04:06 UTC, tnagorra commented on src/views/ProjectEdit/ProjectDetailsForm/index.tsx
> +                                disabled
It's better to make this readOnly

2021-03-25 10:59 UTC, subinasr commented on src/views/ProjectEdit/styles.scss
> +    background-color: white;
Seconded

2021-03-25 11:00 UTC, subinasr approved these changes

2021-03-30 05:30 UTC, AdityaKhatri commented on src/components/general/AddStakeholdersButton/index.tsx
> +import Button from '#rsca/Button';
Use Button from dui

2021-03-30 05:30 UTC, AdityaKhatri commented on src/components/general/AddStakeholdersButton/index.tsx
> +import React from 'react';
Also, if this component is used in current project panel, then replicate it to work with previous pages as well.

2021-03-30 05:31 UTC, AdityaKhatri commented on src/components/general/AddStakeholdersButton/index.tsx
> +import modalize from '#rscg/Modalize';
Instead of modalize, use Modal and useModalState hook with new Button component

2021-03-30 05:31 UTC, AdityaKhatri commented on src/components/general/OrganizationList/index.tsx
> +import Icon from '#rscg/Icon';
Use ReactIcons instead of Icon component

2021-03-30 05:51 UTC, AdityaKhatri commented on src/views/Project/Details/General/index.js
> +import AddStakeholdersButton from '#components/general/AddStakeholdersButton';
Lets duplicate this and create a new deep ui look alike design for stakeholders modal

2021-03-30 05:52 UTC, AdityaKhatri commented on src/views/ProjectEdit/ProjectDetailsForm/index.tsx
> +import Icon from '#rscg/Icon';
Use react icons

2021-03-30 05:52 UTC, AdityaKhatri commented on src/views/ProjectEdit/ProjectDetailsForm/index.tsx
> +import TextArea from '#rsci/TextArea';
Use deep-ui

2021-03-31 08:48 UTC, subinasr approved these changes

2021-04-08 04:41 UTC, tnagorra commented on src/views/ProjectEdit/ProjectDetailsForm/index.tsx
> +        const organizations = groupedOrganizations[key] ?? [];
Empty list should not be created here!

2021-04-14 04:04 UTC, tnagorra commented on src/views/ProjectEdit/ProjectDetailsForm/index.tsx
> +    const handleFaramChange = useCallback((newValues, newErrors) => {
Need to define types for function arguments

2021-04-14 04:04 UTC, tnagorra commented on src/views/ProjectEdit/ProjectDetailsForm/index.tsx
> +    const handleFaramValidationSuccess = useCallback((_, values) => {
Need to define types for function arguments

2021-04-14 04:04 UTC, tnagorra commented on src/views/ProjectEdit/ProjectDetailsForm/index.tsx
> +    const organizationListRendererParams = useCallback((key, v) => {
Need to define types for function arguments

2021-04-14 06:51 UTC, tnagorra requested changes
Need to fix behavior when creating a new project

2021-04-15 09:39 UTC, tnagorra approved these changes

2021-04-15 09:42 UTC, merged