Add Export Selection Options
the-deep/client pull request #1498
Opened 2021-04-06 05:45 UTC by subinasr

- Show Entry Id
- Show Ary Details
- Show Additional Metadata

2021-04-06 11:00 UTC, AdityaKhatri commented on src/views/Export/ExportSelection/ExportTypePane/index.tsx
> +                    />
This should be always shown.

2021-04-06 11:01 UTC, AdityaKhatri requested changes
Waiting for fixes.

2021-04-06 11:06 UTC, subinasr commented on src/views/Export/ExportSelection/ExportTypePane/index.tsx
> +                    />
Done!

2021-04-08 03:47 UTC, tnagorra approved these changes

2021-04-08 09:43 UTC, merged