Change data structure of filters saved and use in filter form
the-deep/client pull request #1501
Opened 2021-04-09 11:06 UTC by AdityaKhatri

Depends on: https://github.com/the-deep/server/pull/722

2021-04-12 10:25 UTC, tnagorra commented on src/views/AnalysisModule/Analysis/index.tsx
> +    useEffect(() => {
Please add a note why we are fetching/re-triggering on modifedAt change

2021-04-12 10:26 UTC, tnagorra commented on src/views/AnalysisModule/Analysis/index.tsx
> +                onAnalysisPillarDelete();
Shouldn't this be before pillarGetTrigger

2021-04-12 10:27 UTC, tnagorra commented on src/views/AnalysisModule/AnalysisEditModal/index.tsx
> +        const newAnalysisPillar = [...analysisPillar].map(ap => ({
```suggestion
        const newAnalysisPillar = analysisPillar.map(ap => ({
```

2021-04-12 10:27 UTC, tnagorra commented on src/views/AnalysisModule/AnalysisEditModal/index.tsx
>      const onValidationSuccess = useCallback((finalValues) => {
Please add typings for finalValues

2021-04-12 10:32 UTC, tnagorra commented on src/views/PillarAnalysis/index.tsx
> +
Why not add this logic on onCompleted?

2021-04-12 10:32 UTC, tnagorra requested changes
Needs some re-work!

2021-04-13 04:20 UTC, samshara commented on src/views/AnalysisModule/Analysis/AnalysisPillar/index.tsx
> +        pendingPillarDelete,
this variable is unused

2021-04-13 04:27 UTC, samshara commented on src/views/AnalysisModule/Analysis/AnalysisPillar/index.tsx
>      // setIsCompleted to be used when the status is passed by API
can't we just use declare completed as false here

2021-04-13 06:09 UTC, merged