Feature/entry review remove approve verify 2
the-deep/client pull request #1574
Opened 2021-04-30 04:43 UTC by AdityaKhatri

2021-04-30 05:20 UTC, frozenhelium approved these changes

2021-04-30 06:14 UTC, tnagorra commented on src/redux/initial-state/dev-lang.json
> +        "-56701570": "{assigner} verified aREvyn {entry} in project {projectName}.",
```suggestion
        "-56701570": "{assigner} verified an {entry} in project {projectName}.",
```

2021-04-30 06:15 UTC, tnagorra commented on src/redux/initial-state/dev-lang.json
> +        "-81087776": "{controlledCount} verified out of {entriesCount} entries",
```suggestion
        "-81087776": "{controlledCount} controlled out of {entriesCount} entries",
```

2021-04-30 06:15 UTC, tnagorra commented on src/redux/initial-state/dev-lang.json
> +        "-11119478": "{controlled} out of {total} entries are verified in this category.",
```suggestion
        "-11119478": "{controlled} out of {total} entries are controlled in this category.",
```

2021-04-30 06:21 UTC, tnagorra commented on src/components/general/ToggleEntryControl/index.tsx
> +        )?.badges.some(v => v === 0),
```suggestion
        )?.badges.some(v => v === SOME_ENUM_HERE),
```

2021-04-30 06:21 UTC, tnagorra requested changes
Some problem with translations

2021-05-04 11:28 UTC, tnagorra approved these changes

2021-05-06 13:03 UTC, merged