Feature/new form in analysis edit
the-deep/client pull request #1598
Opened 2021-05-11 03:32 UTC by frozenhelium

2021-05-11 04:15 UTC, AdityaKhatri approved these changes

2021-05-11 04:18 UTC, tnagorra commented on src/views/Home/index.tsx
> +                                    name=""
```suggestion
                                    name={undefined}
```

2021-05-11 05:33 UTC, tnagorra commented on src/components/viz/Timeline/index.tsx
> +        minDomainExtent = 7776000000, // 3 monts
```suggestion
        minDomainExtent = 7776000000, // 3 months
```

2021-05-11 05:36 UTC, tnagorra commented on src/constants/styleProperties.js
> +        // spacingUltraLarge: '6.89rem',
Why add these comments? Please block comment if necessary to comment

2021-05-11 05:43 UTC, tnagorra commented on src/views/AnalysisModule/AnalysisEditModal/index.tsx
> +            )}
This is dangerous!

2021-05-11 05:43 UTC, tnagorra commented on src/views/AnalysisModule/AnalysisEditModal/index.tsx
> +                )}
This may be dangerous

2021-05-11 05:43 UTC, tnagorra commented on src/views/AnalysisModule/AnalysisEditModal/index.tsx
> +                        data={value.analysisPillar ?? []}
List should handle this

2021-05-13 12:36 UTC, tnagorra requested changes

2021-05-13 12:36 UTC, tnagorra commented on src/views/Home/Assignment/index.tsx
> +                )}
Shouldn't we also check for loading state?

2021-05-13 12:36 UTC, tnagorra commented on src/views/Home/RecentActivity/index.tsx
> +                )}
Shouldn't we also check for loading state.

Maybe introduce props:
- loading
- emptyElement
- loadingElement

inside list?

2021-05-13 12:36 UTC, tnagorra commented on src/views/Home/index.tsx
> +                        )}
What about loading state or errored state?

2021-05-14 07:59 UTC, samshara approved these changes

2021-05-14 11:52 UTC, closed without merging