Add back button
the-deep/client pull request #166
Opened 2018-08-13 11:58 UTC by samshara

2018-08-15 10:24 UTC, tnagorra requested changes
![image](https://user-images.githubusercontent.com/4928045/44143983-87092876-a0a5-11e8-9a0f-ad277865fbcd.png)

Tooltip "Show table" doesn't make sense now.
Should have been "Go to leads" or something similar.

2018-08-16 13:02 UTC, AdityaKhatri commented on src/views/LeadsViz/index.js
> +<<<<<<< Updated upstream
LoL

2018-08-16 13:02 UTC, AdityaKhatri commented on src/views/LeadsViz/index.js
> +>>>>>>> Stashed changes
LOLOL

2018-08-16 13:02 UTC, AdityaKhatri commented on src/views/LeadsViz/index.js
> +=======
LOL

2018-09-14 10:50 UTC, closed without merging