Use new table in user and user groups in project edit
the-deep/client pull request #1661
Opened 2021-05-15 11:32 UTC by AdityaKhatri

2021-05-18 10:02 UTC, tnagorra commented on src/views/ProjectEdit/Users/UserGroupList/index.tsx
> +                className={styles.button}
Please add title

2021-05-18 10:03 UTC, tnagorra commented on src/views/ProjectEdit/Users/UserList/index.tsx
> +}
Why was this not reused?

2021-05-18 10:04 UTC, tnagorra requested changes
Need to reuse ActionCell

2021-05-18 10:26 UTC, AdityaKhatri commented on src/views/ProjectEdit/Users/UserList/index.tsx
> +}
too tired?

2021-05-18 11:08 UTC, AdityaKhatri commented on src/views/ProjectEdit/Users/UserList/index.tsx
> +}
done :crying_cat_face:

2021-05-20 05:38 UTC, tnagorra approved these changes

2021-05-20 06:00 UTC, merged