Add ChangePasswordModal to facilitate user password change
the-deep/client pull request #1735
Opened 2021-06-10 12:08 UTC by samshara

- Addresses #1682
- Depends on https://github.com/the-deep/server/pull/786
## Changes
* Create ChangePasswordModal to handle password change
* Use it in MyProfile page

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

## Note
Added FIXME comments to replace TextInput with PasswordInput when it is availabe in deep-ui

2021-06-10 14:27 UTC, AdityaKhatri requested changes

2021-06-10 14:27 UTC, AdityaKhatri commented on src/components/general/ChangePasswordButton/index.tsx
> +import { Button } from '@the-deep/deep-ui';
Move and group library imports at the top.

2021-06-10 14:27 UTC, AdityaKhatri commented on src/components/general/ChangePasswordButton/index.tsx
> +                onClick={toggleModalShow}
This can only use showModal, so lets use that.

2021-06-10 14:27 UTC, AdityaKhatri commented on src/components/general/ChangePasswordModal/index.tsx
> +            lengthSmallerThanCondition(129),
I think this is 120 right? Could you confirm what is done in the backend.
@k9845 ?

2021-06-11 02:22 UTC, k9845 commented on src/components/general/ChangePasswordModal/index.tsx
> +            lengthSmallerThanCondition(129),
```suggestion
            lengthGreaterThanCondition(8),
            lengthSmallerThanCondition(128),
```
This should be according to backend

2021-06-11 04:20 UTC, merged