Use dnd for sorting analytical statements
the-deep/client pull request #1770
Opened 2021-06-19 16:14 UTC by AdityaKhatri

- Addresses https://github.com/the-deep/client/issues/1685

## Changes

* Use dnd kit for drag and drop

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2021-06-30 03:36 UTC, tnagorra reviewed
There are some minor problems but looks good!

2021-07-01 06:02 UTC, tnagorra requested changes

2021-07-01 06:02 UTC, tnagorra commented on src/newViews/PillarAnalysis/index.tsx
> +        const orderedValues = [...newValues].map((v, i) => ({ ...v, order: i }));
Why copy the array?

2021-07-01 07:01 UTC, AdityaKhatri commented on src/newViews/PillarAnalysis/index.tsx
> +        const orderedValues = [...newValues].map((v, i) => ({ ...v, order: i }));
i am but a simple man

2021-07-01 09:00 UTC, closed without merging