Add EntriesStats component to show sources/entries statistics
the-deep/client pull request #1773
Opened 2021-06-21 10:53 UTC by samshara

- fixes https://github.com/the-deep/client/issues/1752
## Changes

* Add EntriesStats component to show sources/entries statistics

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-06-21 18:43 UTC, subinasr approved these changes

2021-06-28 13:15 UTC, tnagorra requested changes

2021-06-28 13:15 UTC, tnagorra commented on src/components/general/EntriesStats/index.tsx
> +    [stats]);
Let's just use mapToList

2021-06-28 15:05 UTC, tnagorra approved these changes

2021-06-29 11:50 UTC, samshara commented
https://github.com/the-deep/client/pull/1828

2021-06-29 11:50 UTC, closed without merging