Add SourcesFilter component to select filter options for sources
the-deep/client pull request #1778
Opened 2021-06-24 11:29 UTC by samshara

- fixes https://github.com/the-deep/client/issues/1753

## Changes

* Add SourcesFilter component
* Add dropdown to show other filters

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-06-25 03:01 UTC, AdityaKhatri requested changes

2021-06-25 03:01 UTC, AdityaKhatri commented on src/components/general/SourcesFilter/index.tsx
> +        failureHeader: 'sources filter',
Use translation

2021-06-25 03:01 UTC, AdityaKhatri commented on src/components/general/SourcesFilter/index.tsx
> +        search: [],
Can we add all the lead filters that are possible to add right now?
Like priority, status, etc.

2021-06-28 15:07 UTC, tnagorra approved these changes

2021-06-28 15:26 UTC, tnagorra approved these changes

2021-06-29 11:49 UTC, closed without merging

2021-06-29 11:50 UTC, samshara commented
the commits from this branch were moved to https://github.com/the-deep/client/pull/1828