Feature/version check pillar analysis
the-deep/client pull request #1779
Opened 2021-06-25 03:32 UTC by tnagorra

- Related to https://github.com/the-deep/client/issues/1766
- Depends on https://github.com/the-deep/server/pull/805

## Changes

- Shows notification that data is overridden
- Shows data

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2021-06-28 14:38 UTC, samshara approved these changes

2021-07-07 16:09 UTC, AdityaKhatri requested changes

2021-07-07 16:09 UTC, AdityaKhatri commented on src/newViews/PillarAnalysis/index.tsx
> +    // TODO: pass pristine value
remove todo

2021-07-07 16:15 UTC, AdityaKhatri approved these changes

2021-07-08 05:44 UTC, merged