Add sort behavior in primary and secondary tagging
the-deep/client pull request #1836
Opened 2021-07-05 09:20 UTC by AdityaKhatri

- Addresses https://github.com/the-deep/client/issues/1804, https://github.com/the-deep/client/issues/1827

## Changes

* Add ordering of widgets in primary and secondary tagging

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [ ] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-07-05 09:33 UTC, tnagorra commented on src/newViews/AnalyticalFramework/PrimaryTagging/utils.ts
> +) {
We should only attempt odering on non temporary section and widget

2021-07-05 09:34 UTC, tnagorra requested changes
Need to fix typing issues before merge.

2021-07-05 10:37 UTC, subinasr approved these changes

2021-07-06 04:21 UTC, samshara approved these changes

2021-07-06 05:24 UTC, tnagorra approved these changes

2021-07-06 05:35 UTC, merged