Add response error to form error transformer
the-deep/client pull request #1860
Opened 2021-07-08 09:11 UTC by tnagorra

## Changes

- Fix filter apply action for analysis pillar
- Set server error from analysis pillar update
- Pass response errors to onFailure

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-07-08 09:21 UTC, samshara requested changes

2021-07-08 09:21 UTC, samshara commented on src/rest/index.js
> +            (error) => error.transformedValue,
```suggestion
            error => error.key,
            error => error.transformedValue,
```

2021-07-08 09:21 UTC, samshara commented on src/rest/index.js
> +            (key) => key,
```suggestion
            key => key,
```

2021-07-09 04:21 UTC, AdityaKhatri requested changes

2021-07-09 04:21 UTC, AdityaKhatri commented on src/rest/index.js
> +    if (Array.isArray(formSchema)) {
use isList from fujs?
Its the same now, but we might add more checks later on.

2021-07-09 08:07 UTC, merged