Fix column widths in sources table
the-deep/client pull request #1919
Opened 2021-07-19 09:08 UTC by AdityaKhatri

## Changes

* Define column widths

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-07-19 17:43 UTC, subinasr reviewed
![image](https://user-images.githubusercontent.com/51225380/126203361-40cb4c49-3d28-489e-94c0-33766e0d2a5d.png)
I think the action column has some styling issue?

2021-07-20 02:04 UTC, AdityaKhatri commented
> ![image](https://user-images.githubusercontent.com/51225380/126203361-40cb4c49-3d28-489e-94c0-33766e0d2a5d.png)
> I think the action column has some styling issue?

Yes @subinasr , I've created another issue for it: https://github.com/the-deep/client/issues/1922

2021-07-20 03:34 UTC, subinasr approved these changes

2021-07-20 04:53 UTC, tnagorra requested changes

2021-07-20 04:53 UTC, tnagorra commented on src/newViews/Tagging/Sources/SourcesTable/BulkActions/styles.scss
> +    background-color: #414141;
Are we hard-coding the color values?

2021-07-20 04:53 UTC, tnagorra commented on src/newViews/Tagging/Sources/SourcesTable/BulkActions/styles.scss
> +    background-color: #414141;
Similar comment for radius and min-width

2021-07-20 04:53 UTC, tnagorra commented on src/newViews/Tagging/Sources/SourcesTable/index.tsx
> +
Why create a separate function.

2021-07-20 06:18 UTC, tnagorra approved these changes

2021-07-20 07:10 UTC, merged