Create LeadGroupSelectInput component
the-deep/client pull request #1930
Opened 2021-07-20 09:25 UTC by subinasr

- Addresses #1867

## Changes

* Create Lead group select input component
## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2021-07-20 10:03 UTC, tnagorra approved these changes

2021-07-20 12:22 UTC, AdityaKhatri commented on src/newComponents/input/LeadGroupSelectInput/index.tsx
> +        url: 'server://lead-groups/',
We need to have lead-groups filtered by projectId

2021-07-20 12:22 UTC, AdityaKhatri requested changes
Add project scoping

2021-07-21 05:32 UTC, samshara approved these changes

2021-07-22 08:05 UTC, AdityaKhatri approved these changes

2021-07-22 08:06 UTC, merged