Feature/files upload
the-deep/client pull request #1931
Opened 2021-07-20 12:41 UTC by samshara

- fies #1854

## Changes

* Add files upload in parallel
* Support Google Drive file upload
* Support Dropbox file upload

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [ ] translations

2021-07-21 05:49 UTC, subinasr approved these changes

2021-07-21 10:32 UTC, tnagorra requested changes

2021-07-21 10:32 UTC, tnagorra commented on src/utils/common.js
> +    if (bytes === 0) return '0 Bytes';
```suggestion
    if (bytes === 0) {
        return '0 B';
    }
```

2021-07-21 10:32 UTC, tnagorra commented on src/utils/common.js
> +    const dm = decimals < 0 ? 0 : decimals;
```suggestion
    const dm = Math.min(0, decimals);
```

2021-07-21 10:32 UTC, tnagorra commented on src/utils/common.js
> +    return `${parseFloat((bytes / (k ** i)).toFixed(dm))} ${sizes[i]}`;
We should not return formatted string.
Instead lets return an object with value and suffix so that Numeral can show it later on.

2021-07-21 10:32 UTC, tnagorra commented on src/utils/common.js
> +    return `${parseFloat((bytes / (k ** i)).toFixed(dm))} ${sizes[i]}`;
Or, even better let's just create a component to render this.
Ref: https://github.com/idmc-labs/helix-client/blob/develop/src/components/Downloads/DownloadedItem/index.tsx

2021-07-21 10:32 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/types.ts
> +}
```suggestion
export type GoogleFileType = Omit<FileLike, 'file'> & {
    mimeType: string;
}

export type DropboxFileType = Omit<FileLike, 'file'> & {
    link: string;
}
```

2021-07-21 10:32 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/UploadedList/UploadedItem/index.tsx
> +        <div>{props.name}{props.isUploaded ? 'uploaded' : 'processing'}</div>
Shouldn't they be in multiple lines?
Isn't there any linter error?

2021-07-21 10:32 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/UploadItem/index.tsx
> +    return <></>;
```suggestion
    return null;
```

2021-07-21 10:32 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/UploadItem/index.tsx
> +    }, [active, uploadFile, data]);
I think we can use useRequest with skip instead of useLazyRequest.

2021-07-21 10:32 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/GoogleDriveFilesUpload/index.tsx
> +            )}
I don't think we need this check for files and files length

2021-07-21 10:32 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/DropboxFilesUpload/index.tsx
> +        onChange(values);
Why do we need to call onChange?

2021-07-21 10:32 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/FilesUpload/index.tsx
> +            )}
The file upload mechanism should be global IMO. (shared for drive, dropbox and file uploads)

What do you guys think @AdityaKhatri @frozenhelium

2021-07-21 10:32 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/FilesUpload/index.tsx
> +                value={fileList}
Do we need to pass value to FileInput if we immediately upload these files?

2021-07-22 12:03 UTC, tnagorra requested changes

2021-07-22 12:03 UTC, tnagorra commented on src/utils/common.js
> +        value: parseFloat((bytes / (k ** i)).toFixed(dm)),
We do not do parseFloat here.
We let that decision for Numeral (which can handle dynamic precision as well)

2021-07-22 12:03 UTC, tnagorra commented on src/utils/common.js
> +    const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
```suggestion
    const sizes = ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
```

2021-07-22 12:03 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/DropboxFilesUpload/index.tsx
> +    onChange: (v: FileLike[]) => void;
Shouldn't this be onAdd or onUpload?

2021-07-22 12:03 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/FilesUpload/index.tsx
> +    onChange: (v: FileLike[]) => void;
Shouldn't this be onAdd or onUpload?

2021-07-22 12:03 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/GoogleDriveFilesUpload/index.tsx
> +    onChange: (v: FileLike[]) => void;
Shouldn't this be onUpload or onAdd?

2021-07-22 12:03 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/GoogleDriveFilesUpload/index.tsx
> +    };
Let's use useCallback

2021-07-22 12:03 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/GoogleDriveFilesUpload/index.tsx
> +    const accessToken = useRef<string>();
```suggestion
    const accessToken = useRef<string | undefined>();
```

2021-07-22 12:03 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/Upload/UploadItem/index.tsx
> +    }, [retrigger]);
We can re-trigger? How does this work?
Simply moving the file from failedFiles to files?

2021-07-23 07:02 UTC, tnagorra requested changes

2021-07-23 07:02 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/FilesUploaded/FilesSearchInput/index.tsx
> +        }
Why pass  filtered files outside?
This should be handled during render

2021-07-23 07:02 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/FilesUploaded/index.tsx
> +    }, []);
Do we need to create a function? Why not just alias

const handleSearchFiles = setSearchResults;

2021-07-23 07:02 UTC, tnagorra commented on src/newViews/Tagging/Sources/BulkUpload/FilesUploaded/index.tsx
> +                />
The search state should be moved to this parent component and parent should implement the filtering logic

2021-07-23 08:25 UTC, merged