Add Region Selec Input in Geo Areas
the-deep/client pull request #1944
Opened 2021-07-21 12:04 UTC by subinasr

- Addresses #1788 

## Changes

* Create RegionSelectInput for Geo Areas
* Use RegionSelectInput to add regions to a project

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [ ] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2021-07-22 11:34 UTC, tnagorra commented on src/newViews/ProjectEdit/GeoAreas/RegionMapList/index.tsx
> +                    {isDefined(regionResponse) && regionResponse?.regions.length < 1 && (
```suggestion
                    {regionResponse && regionResponse?.regions.length < 1 && (
```

2021-07-22 11:52 UTC, tnagorra requested changes

2021-07-22 11:52 UTC, tnagorra commented on src/newViews/ProjectEdit/GeoAreas/RegionMapList/index.tsx
> +    const handleRegionSelectChange = useCallback((val) => {
Please add type for val

2021-07-26 05:12 UTC, AdityaKhatri approved these changes

2021-07-26 05:13 UTC, merged