Remove un-necessary files
the-deep/client pull request #1953
Opened 2021-07-23 08:58 UTC by tnagorra

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2021-07-30 05:13 UTC, thenav56 commented on .github/workflows/ci.yml
> -      - uses: actions/checkout@v2
This is needed to fetch the-deep/client

2021-07-30 05:44 UTC, frozenhelium approved these changes

2021-08-02 07:55 UTC, tnagorra commented on .github/workflows/ci.yml
> -      - uses: actions/checkout@v2
Thanks!

2021-08-02 16:03 UTC, AdityaKhatri approved these changes

2021-08-02 16:11 UTC, AdityaKhatri requested changes
Rename base-react-app to DEEP and properly maintain brand name.
Also, please rebase with develop-deep and send a PR.

2021-08-02 16:11 UTC, AdityaKhatri commented on package.json
> +    "name": "base-react-app",
Rename to DEEP

2021-08-02 16:11 UTC, AdityaKhatri commented on package.json
> +    "description": "Base React Application",
Rename to DEEP

2021-08-02 16:11 UTC, AdityaKhatri commented on package.json
> +        "url": "git+https://github.com/togglecorp/base-react-app.git"
Rename to DEEP

2021-08-02 16:11 UTC, AdityaKhatri commented on package.json
> +        "url": "https://github.com/togglecorp/base-react-app/issues"
Rename to DEEP

2021-08-02 16:13 UTC, AdityaKhatri commented on .gitignore
> -vendor/
Add this back for now

2021-08-03 03:20 UTC, tnagorra commented on package.json
> +        "url": "https://github.com/togglecorp/base-react-app/issues"
okay sir!

2021-08-04 16:24 UTC, frozenhelium approved these changes

2021-08-04 16:36 UTC, AdityaKhatri approved these changes

2021-08-04 16:37 UTC, merged