Add Success/Confirmation message to Analysis Module
the-deep/client pull request #1999
Opened 2021-08-04 13:10 UTC by subinasr

- Addresses #3644

## Changes

* Add success message while adding, editing and deleting analysis

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2021-08-04 16:53 UTC, AdityaKhatri requested changes

2021-08-04 16:53 UTC, AdityaKhatri commented on src/newViews/AnalysisModule/AnalysisEditModal/index.tsx
> +            });
Instead of a conditional inside the _ts function, creating separate notify will show the items in string management page

2021-08-04 16:53 UTC, AdityaKhatri commented on src/newViews/AnalysisModule/index.tsx
> +                    message: _ts('analysis', 'analysisDeleteSuccessful'),
Make sure this is added from string management.

2021-08-05 08:44 UTC, tnagorra requested changes

2021-08-05 08:44 UTC, tnagorra commented on src/constants/viewsAcl.js
> +);
You should rebase the pull request. These changes are already merged on develop

2021-08-05 08:44 UTC, tnagorra commented on src/redux/initial-state/dev-lang.json
> +        "-82264498": "Analysis successfully deleted"
```suggestion
        "-47459866": "Analysis successfully edited.",
        "-82264498": "Analysis successfully deleted."
```

2021-08-06 05:37 UTC, tnagorra submitted a review, later dismissed

2021-08-10 08:26 UTC, AdityaKhatri approved these changes, later dismissed

2021-08-10 08:27 UTC, AdityaKhatri approved these changes

2021-08-10 08:36 UTC, AdityaKhatri approved these changes

2021-08-10 08:36 UTC, merged