Setup Exports Page
the-deep/client pull request #2001
Opened 2021-08-04 16:43 UTC by subinasr

- Addresses #1963

## Changes

* Setup Exports Page

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2021-08-04 16:54 UTC, AdityaKhatri requested changes, later dismissed

2021-08-04 16:54 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/index.tsx
> +type ExportType = 'export-history' | 'export-assessment-history';
```suggestion
type ExportType = 'export-entry-history' | 'export-assessment-history';
```

2021-08-04 16:54 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/index.tsx
> +    const [activeTab, setActiveTab] = useState<ExportType>('export-history');
```suggestion
    const [activeTab, setActiveTab] = useState<ExportType>('export-entry-history');
```

2021-08-04 16:54 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/styles.scss
> +                    margin: var(--spacing-small);
```suggestion
                    margin: var(--dui-spacing-small);
```

2021-08-05 08:45 UTC, tnagorra commented on src/newViews/Tagging/Export/index.tsx
> +                                variant="secondary"
Please disable this button

2021-08-05 08:46 UTC, tnagorra requested changes

2021-08-05 08:46 UTC, tnagorra commented on src/newViews/Tagging/Export/index.tsx
> +                                variant="tertiary"
Please disable this button

2021-08-06 05:15 UTC, tnagorra approved these changes, later dismissed

2021-08-06 05:31 UTC, samshara approved these changes, later dismissed

2021-08-09 03:41 UTC, samshara approved these changes

2021-08-09 03:44 UTC, merged