Add export history table and filter component
the-deep/client pull request #2041
Opened 2021-08-18 12:33 UTC by samshara

- fixes #1964

## Changes

* Fetch export and list it in table
* Add export filter

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-08-19 08:36 UTC, AdityaKhatri requested changes

2021-08-19 08:36 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/Actions/index.tsx
> +            </QuickActionButton>
hide this for now

2021-08-19 08:36 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/Actions/index.tsx
> +export interface Props<T extends number> {
As this is exclusively used for export page, we don't need a generic

2021-08-19 08:36 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/Filter/index.tsx
> +            <DateInput
Shouldn't this be a date range filter?

2021-08-19 08:36 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/Filter/index.tsx
> +            </Button>
Lets filter directly, instead of clicking on filter button
Used debounced value for search

2021-08-19 08:36 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/index.tsx
> +        : `-${validSorting.name}`;
useMemo

2021-08-19 08:36 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/index.tsx
> +    }, []);
hide this for now

2021-08-19 08:36 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/index.tsx
> +        };
We have createDateColumn utility already

2021-08-19 08:36 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/index.tsx
> +            id: 'exportedAt',
Sort functionality is not working with exported_at

2021-08-19 08:36 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/index.tsx
> +                <Table
Use TableView

2021-08-19 15:20 UTC, AdityaKhatri requested changes

2021-08-19 15:20 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/index.tsx
> +                    />),
Lets use react-icons for these

2021-08-19 15:20 UTC, AdityaKhatri commented on src/newViews/Tagging/Export/ExportHistory/index.tsx
> +                children: statusLabelMap[data.status],
We cannot download for the moment. Lets create a separate renderer for that to switch between options.

2021-08-20 08:25 UTC, tnagorra requested changes

2021-08-20 08:25 UTC, tnagorra commented on src/newViews/Tagging/Export/ExportHistory/index.tsx
> +        },
Please memoize this

2021-08-20 08:25 UTC, tnagorra commented on src/newViews/Tagging/Export/ExportHistory/Actions/index.tsx
> +import React, { useCallback } from 'react';
Maybe rename to TableActions? Actions can be a very generic name

2021-08-23 02:23 UTC, AdityaKhatri approved these changes

2021-08-23 02:24 UTC, merged