Add create new assessment export popup
the-deep/client pull request #2046
Opened 2021-08-19 09:59 UTC by samshara

- fixes #1968

## Changes

* Create a new assessment modal
* Show modal when new assessment button is clicked

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2021-08-20 08:17 UTC, tnagorra requested changes

2021-08-20 08:17 UTC, tnagorra commented on src/newViews/Tagging/Export/index.tsx
> +        isNewAssessmentModalShown,
```suggestion
        newAssessmentModalShown,
```

2021-08-20 08:17 UTC, tnagorra commented on src/newViews/Tagging/Export/NewAssessmentExport/AssessmentsExportSelection/index.tsx
> +        setExportClass(newExportClass);
All of these can be derived from the export context. So, we may not need to store these

2021-08-20 08:17 UTC, tnagorra commented on src/newViews/Tagging/Export/NewAssessmentExport/AssessmentsExportSelection/index.tsx
> +                        </Button>
Let's disable this if not used

2021-08-23 02:34 UTC, AdityaKhatri approved these changes

2021-08-23 02:35 UTC, merged