Feature/entries in source table
the-deep/client pull request #2131
Opened 2021-09-10 09:22 UTC by subinasr

- Addresses #3986 , #3987 , #3989

## Changes
 * Add entries in sources table
 * Add entry delete functionality
 
## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2021-09-16 10:34 UTC, samshara approved these changes, later dismissed

2021-09-21 05:00 UTC, tnagorra reviewed
IDK if this PR is complete

2021-09-23 18:17 UTC, subinasr commented
> IDK if this PR is complete

2021-09-23 18:46 UTC, subinasr commented
@tnagorra Can you tell me why you think it's incomplete?

2021-09-28 04:12 UTC, AdityaKhatri commented on app/views/Project/Tagging/Sources/components/EditableEntry/index.tsx
> +                console.error(gqlError);
This is not required. Remove from both mutations

2021-09-28 07:56 UTC, samshara commented on app/views/Project/Tagging/Sources/SourcesGrid/EntryCard/index.tsx
> +    }, [projectId, entry.id]);
add ```deleteEntry``` as dependency to useCallback hook

2021-09-28 07:56 UTC, samshara commented on app/views/Project/Tagging/Sources/components/EditableEntry/index.tsx
> +    }, [projectId, entry.id]);
add ```deleteEntry``` to useCallback hook dependency

2021-09-28 10:43 UTC, tnagorra requested changes

2021-09-28 10:43 UTC, tnagorra commented on app/views/Project/Tagging/Sources/components/EditableEntry/index.tsx
> +            disabled={deleteEntryPending}
Should also be disabled on edit mode.
Let's disable all other actions on edit mode

2021-10-02 12:01 UTC, merged