Use graphql for recent projects
the-deep/client pull request #2150
Opened 2021-09-15 08:17 UTC by subinasr

- Addresses #3982

## Changes

* Use graphql to fetch recent projects

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2021-09-16 10:14 UTC, samshara submitted a review, later dismissed

2021-09-19 03:48 UTC, AdityaKhatri requested changes
ProjectItem is not getting appropriate props to render all the items it needs.
Selection of project is broken.

2021-09-21 04:58 UTC, tnagorra requested changes

2021-09-21 04:58 UTC, tnagorra commented on app/views/Home/index.tsx
> +        }
Always pull `id` even if it is not used.
This helps apollo to udpate the normalized cache

2021-09-21 04:58 UTC, tnagorra commented on app/views/Home/index.tsx
> +          }
id is missing

2021-09-21 04:58 UTC, tnagorra commented on app/views/Home/index.tsx
> +        }
id is missing

2021-09-21 04:58 UTC, tnagorra commented on app/views/Home/index.tsx
> +          }
Pull `id` if it is available

2021-09-24 09:41 UTC, AdityaKhatri approved these changes

2021-09-24 09:41 UTC, merged