Fix styling in widget forms in secondary tagging
the-deep/client pull request #2177
Opened 2021-10-06 08:30 UTC by subinasr

## Changes

* Make controlled expandable container in Organigram Widget Form
* Fix styling in widget forms

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2021-10-06 08:41 UTC, tnagorra requested changes

2021-10-06 08:41 UTC, tnagorra commented on app/views/AnalyticalFramework/FrameworkForm/components/WidgetEditor/OrganigramWidgetForm/index.tsx
> +    );
Let's remove the console.warn that was meant for debugging

2021-10-06 08:41 UTC, tnagorra commented on app/views/AnalyticalFramework/FrameworkForm/components/WidgetEditor/OrganigramWidgetForm/index.tsx
> +
Let's remove this comment

2021-10-06 09:15 UTC, samshara commented on app/views/AnalyticalFramework/FrameworkForm/components/WidgetEditor/OrganigramWidgetForm/index.tsx
> +            console.warn('I am inside handle change');
remove console.warn

2021-10-06 09:15 UTC, samshara commented on app/views/AnalyticalFramework/FrameworkForm/components/WidgetEditor/OrganigramWidgetForm/index.tsx
> +        expanded,
```suggestion
      handleNodeExpansionChange,
```

2021-10-06 09:43 UTC, samshara approved these changes

2021-10-07 04:56 UTC, AdityaKhatri approved these changes

2021-10-07 04:58 UTC, merged