Feature/entries dashboard
the-deep/client pull request #2197
Opened 2021-10-26 10:36 UTC by AdityaKhatri

## Changes

* Add visualization settings form in framework creation flow
* Show dashboard if dashboard is enabled for the project
* Add ability to share public url and change its setting

Depends on https://github.com/the-deep/server/pull/996

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-10-27 05:45 UTC, tnagorra requested changes

2021-10-27 05:45 UTC, tnagorra commented on app/views/AnalyticalFramework/FrameworkForm/index.tsx
> +                    const data = { ...cleanData } as AnalysisFrameworkInputType;
```suggestion
                    const data = cleanData as AnalysisFrameworkInputType;
```

2021-10-27 05:45 UTC, tnagorra commented on app/views/AnalyticalFramework/FrameworkForm/index.tsx
> +    }, [onStatsConfigChange]);
Why transform these here? It would be better to create a wrapper input instead

2021-10-27 05:45 UTC, tnagorra commented on app/views/Project/Tagging/Dashboard/index.tsx
> +function ShareModal(props: ShareModalProps) {
Let's move this to a separate component.
Let's also rename ShareModal to indicate what we are sharing using this modal

2021-10-27 05:45 UTC, tnagorra commented on app/views/Project/Tagging/Dashboard/index.tsx
> +                }
Why not handle the else case?

2021-10-27 05:45 UTC, tnagorra commented on app/views/Project/Tagging/Dashboard/index.tsx
> +                }
Shouldn't this always be called?
We may also want to clear the publicUrl if it doesn't exist?

2021-10-27 08:27 UTC, AdityaKhatri commented on app/views/AnalyticalFramework/FrameworkForm/index.tsx
> +    }, [onStatsConfigChange]);
Nah, its a bit too much, we need to write 2 different wrappers, and we'll be removing this in the near future.

2021-10-28 04:20 UTC, tnagorra commented on app/views/AnalyticalFramework/FrameworkForm/index.tsx
> +                        that are already created and saved."
why break strings?

2021-10-28 04:32 UTC, tnagorra submitted a review, later dismissed
Please check deepscan issues

2021-10-28 05:13 UTC, samshara approved these changes

2021-10-28 05:13 UTC, samshara commented on app/views/Project/Tagging/Dashboard/VisualizationShareModal/styles.css
> +    width: 640px;
shouldn't we use some defined widths

2021-10-28 05:37 UTC, AdityaKhatri commented on app/views/Project/Tagging/Dashboard/VisualizationShareModal/styles.css
> +    width: 640px;
Yes, later on

2021-10-28 10:24 UTC, merged