Add explore page stats
the-deep/client pull request #2208
Opened 2021-11-02 04:56 UTC by AdityaKhatri

## Changes

* Add explore page stats

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2021-11-02 05:25 UTC, tnagorra requested changes

2021-11-02 05:25 UTC, tnagorra commented on app/views/ExploreDeep/index.tsx
> +            frameworkTitle: removeNull(datum.analysisFrameworkTitle),
Why use hack?

2021-11-02 05:25 UTC, tnagorra commented on app/views/ExploreDeep/index.tsx
> +                        data={removeNull(data?.projectExploreStats?.topActiveProjects) ?? undefined}
removeNull should be memoized

2021-11-02 05:25 UTC, tnagorra commented on app/views/ExploreDeep/index.tsx
> +                    />
Let's add a FIXME to remove these hard-coded values

2021-11-03 04:27 UTC, subinasr approved these changes

2021-11-03 04:38 UTC, tnagorra approved these changes

2021-11-03 04:58 UTC, merged