Add 'join' button in map view and most used analysis frameworks in Explore Page
the-deep/client pull request #2231
Opened 2021-11-17 08:00 UTC by subinasr

- Addresses #2227 and #2228
- Depends on [feature/recent-framework](https://github.com/the-deep/server/pull/1021)

## Changes
* Add 'join' button in project list in explore page
* Add top 5 most used frameworks in explore page stats

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2021-11-17 08:21 UTC, AdityaKhatri requested changes

2021-11-17 08:21 UTC, AdityaKhatri commented on app/views/ExploreDeep/ActionCell/index.tsx
> +    variant?: 'general' | 'action' | 'primary' | 'secondary' | 'tertiary' | 'transparent';
Add variant type from Button itself instead of redefining it.

2021-11-17 08:21 UTC, AdityaKhatri commented on app/views/ExploreDeep/index.tsx
> +    ), [data?.projectExploreStats?.topActiveFrameworks]);
Remove this if possible. Add reason if else.

2021-11-17 09:34 UTC, samshara approved these changes

2021-11-23 05:03 UTC, AdityaKhatri approved these changes

2021-11-24 06:45 UTC, merged