Integrate badge field in project user item
the-deep/client pull request #2236
Opened 2021-11-24 05:20 UTC by samshara

- fixes  #2235

* Use graphQL API for fetch, delete, edit user 
* Show and edit badge (additional permission)
## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2021-11-24 11:09 UTC, tnagorra requested changes

2021-11-24 11:09 UTC, tnagorra commented on app/views/ProjectEdit/Users/UserList/index.tsx
> +                onDeleteClick: () => handleRemoveUserFromProject(data.id),
We should not create inline functions on cell renderer params

2021-11-24 11:09 UTC, tnagorra commented on app/views/ProjectEdit/Users/UserList/index.tsx
> +                );
We should check if deletion this was successful.
We should also alert if it was not.
Also, deletedUser can be undefined on line 188, which means the deletion failed.
Let's check `ok` to see if there's error

2021-11-24 11:09 UTC, tnagorra commented on app/views/ProjectEdit/Users/UserList/AddUserModal/index.tsx
> +                if (errors && errors[0]) {
Do we need to check for the errors to have an item? can we just not check for length?

2021-11-24 11:09 UTC, tnagorra commented on app/views/ProjectEdit/Users/UserList/AddUserModal/index.tsx
> +                        { variant: 'success' },
What happens if there is no user?

2021-11-24 11:09 UTC, tnagorra commented on app/types/project.tsx
> +type badges = 'QA';
We should get this enum from generated/types.tsx

2021-11-25 09:49 UTC, subinasr approved these changes

2021-11-25 11:18 UTC, merged