Add Assessment Registry using iframe
the-deep/client pull request #2254
Opened 2021-12-01 10:53 UTC by samshara

- Add assessment registry
- Depends on https://github.com/the-deep/client/tree/feature/only-ary

### how to run assessment registry 
1. Deploy the branch https://github.com/the-deep/client/tree/feature/only-ary
2. Update REACT_APP_ASSESSMENT_REGISTRY_END env to the deployed endpoint

If you want to run assessment registry in local environment
1. Copy all the code from (https://github.com/the-deep/client/tree/feature/only-ary) to a client_old folder under [deeper](https://github.com/the-deep/deeper) root directory
2.  Update docker-compose.yml 
```
  client_old:
      image: thedeep/deep-client:latest-old
      build:
        context: ./client_old/
        cache_from:
          - thedeep/deep-client:latest
      tty: true
      env_file:
        - .env
      command: bash -c '/code/scripts/run_develop.sh'
      volumes:
        - ./client_old/:/code
      ports:
        - '3100:3000'
```
3. Update REACT_APP_ASSESSMENT_REGISTRY_END `REACT_APP_ASSESSMENT_REGISTRY_END=http://localhost:3100` 
4. run `docker-compose up`

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2021-12-04 12:21 UTC, tnagorra requested changes

2021-12-04 12:21 UTC, tnagorra commented on app/Base/configs/routes.tsx
> +    visibility: 'is-authenticated', // TODO handle permission
We need to check for permissions using `checkPermissions`

2021-12-04 12:21 UTC, tnagorra commented on app/views/Project/Tagging/Assessments/ActionCell/index.tsx
> +                projectId,
We do not need to pass projectId in most of the cases. It is automatically injected

2021-12-04 12:21 UTC, tnagorra commented on app/views/Project/Tagging/Assessments/EditAssessment/index.tsx
> +            {aryEndpoint && (
Let's add condition on src. and use src definition on 24.

const aryEndpoint = ...;
const src = aryEndpoint ? ... : undefined;

return (
    {src && <iframe />}
)

2021-12-04 12:21 UTC, tnagorra commented on app/views/Project/Tagging/index.tsx
> +                    />
This route is here to load the subNavbarComponents. Please pass them as children

2021-12-05 10:05 UTC, AdityaKhatri approved these changes

2021-12-05 10:05 UTC, merged