Fix/minor issues jan 25
the-deep/client pull request #2359
Opened 2022-01-26 09:33 UTC by AdityaKhatri

## Changes

* Show lead preview on click on the title
* Make assignee editable
* Select entry while going from notifications
* Add ability to change no of items in source listing page

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [X] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2022-01-26 11:07 UTC, samshara approved these changes

2022-01-26 13:03 UTC, tnagorra requested changes, later dismissed

2022-01-26 13:03 UTC, tnagorra commented on app/components/entryReview/EntryComments/Comment/EditCommentForm/index.tsx
> +        mentionedUsers: [requiredCondition],
We may need to use requiredListCondition

2022-01-26 13:03 UTC, tnagorra commented on app/components/entryReview/EntryComments/Comment/EditCommentForm/index.tsx
> +        mentionedUsers: comment.mentionedUsers.map((u) => String(u)),
```suggestion
        mentionedUsers: comment.mentionedUsers.map(String),
```

2022-01-26 13:03 UTC, tnagorra commented on app/components/lead/LeadPreviewButton/index.tsx
> +                        url
Let's fetch `id` for file

2022-01-26 13:03 UTC, tnagorra commented on app/components/lead/LeadPreviewButton/index.tsx
> +                    )}
Why not handle loading state here?

2022-01-27 03:46 UTC, AdityaKhatri commented on app/components/lead/LeadPreviewButton/index.tsx
> +                    )}
it is handled in Message component

2022-01-27 06:26 UTC, samshara approved these changes

2022-01-27 06:29 UTC, merged