Add swap feature for date-range & time-range
the-deep/client pull request #2366
Opened 2022-02-01 10:18 UTC by priyesh777

## Addresses:
- https://github.com/the-deep/client/issues/2339#event-5931222444

## Changes:
- Add a swap feature for the date range inputs and time range inputs 

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2022-02-01 11:47 UTC, tnagorra requested changes

2022-02-01 11:47 UTC, tnagorra commented on app/components/DateRangeInputWrapper/index.tsx
> +    const dateValue = !!value?.startDate && !!value?.endDate;
```suggestion
    const hasDateValue = !!value?.startDate || !!value?.endDate;
```

2022-02-01 11:47 UTC, tnagorra commented on app/components/TimeRangeInputWrapper/index.tsx
> +    const timeValue = !!value?.startTime && !!value?.endTime;
```suggestion
    const hasTimeValue = !!value?.startTime || !!value?.endTime;
```

2022-02-01 11:47 UTC, tnagorra commented on app/components/TimeRangeInputWrapper/index.tsx
> +                    readOnly={readOnly}
Let's hide this button if readOnly is true

2022-02-01 11:47 UTC, tnagorra commented on app/components/DateRangeInputWrapper/index.tsx
> +                    readOnly={readOnly}
Let's hide this button if readOnly is true

2022-02-07 03:48 UTC, tnagorra requested changes

2022-02-07 03:48 UTC, tnagorra commented on app/components/DateRangeInputWrapper/index.tsx
> +            {hasDateValue && (
Let's hide this button if readOnly is true

2022-02-07 03:48 UTC, tnagorra commented on app/components/TimeRangeInputWrapper/index.tsx
> +            {hasTimeValue && (
Let's hide this button if readOnly is true

2022-02-10 05:38 UTC, AdityaKhatri approved these changes

2022-02-10 05:39 UTC, merged