Add sorting ability to users and usergroups in project edit page
the-deep/client pull request #2375
Opened 2022-02-16 10:39 UTC by subinasr

- Addresses #4766
- Depends on https://github.com/the-deep/server/pull/1054

## Changes
* Sort users and usergroups list
* Add a component to select usergroups
* Add graphql to fetch, edit, add and delete usergroups

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2022-02-23 10:08 UTC, tnagorra requested changes

2022-02-23 10:08 UTC, tnagorra commented on app/views/ProjectEdit/Users/UserGroupList/AddUserGroupModal/index.tsx
> +                id: [requiredCondition],
Let's just add a "defaultUndefinedType" on "id".
We do not need to create conditional form

2022-02-28 07:21 UTC, AdityaKhatri requested changes

2022-02-28 07:21 UTC, AdityaKhatri commented on app/views/ProjectEdit/Users/UserGroupList/AddUserGroupModal/NewUsergroupSelectInput/index.tsx
> +import React, { useState, useMemo } from 'react';
Is UsergroupSelectInput being used somewhere else? If not, lets make this the default one, and remove the work new.

2022-03-08 07:05 UTC, merged