Feature/nlp mock data
the-deep/client pull request #2380
Opened 2022-02-19 11:28 UTC by AdityaKhatri

## Changes

* Add mock data for NLP keywords
* Add mapping interface in assisted tagging

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks

2022-02-21 08:35 UTC, samshara commented on app/types/newAnalyticalFramework.ts
> +export const mockAssistedTags = [
adding type info might be useful here

2022-02-21 08:35 UTC, samshara commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/index.tsx
> +            {widget.title}
The title is already visible in the heading. Do we need to display it again?

2022-02-21 08:35 UTC, samshara commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +        value: !!mapping?.find((m) => m.widgetId === widget.clientId && m.widgetType === 'GEO'),
we can use array.some() method here

2022-02-21 08:35 UTC, samshara commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/index.tsx
> +];
this info is repeated across files. A common source would be useful.

2022-02-22 08:14 UTC, priyesh777 submitted a review, later dismissed

2022-02-23 10:54 UTC, tnagorra requested changes

2022-02-23 10:54 UTC, tnagorra commented on app/types/newAnalyticalFramework.ts
> +export const mockAssistedTags: AssistedTag[] = [
Let's add a FIXME comment to remove this

2022-02-23 10:54 UTC, tnagorra commented on app/types/newAnalyticalFramework.ts
> +    widgetPk: string;
Let's add a note why this key is named widgetPk instead of widgetId

2022-02-23 10:54 UTC, tnagorra commented on app/types/newAnalyticalFramework.ts
> +        subColumnKey?: undefined;
Let's just remove this line or change `undefined` to `string`

2022-02-23 10:54 UTC, tnagorra commented on app/types/newAnalyticalFramework.ts
> +];
We may need to define stricter types for these list

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/CheckButton/index.tsx
> +    title: string;
```suggestion
    children: string;
```

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/CheckButton/index.tsx
> +    onTagClick: (key: string) => void;
```suggestion
    onClick: (key: string) => void;
```

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/CheckButton/index.tsx
> +    itemKey: string;
```suggestion
    name: T;
```

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/CheckButton/index.tsx
> +    mappedCount?: number;
Let's rename this to more generic name

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagList/index.tsx
> +const groupKeySelector = (n: CellItem) => n.rowKey;
```suggestion
const groupKeySelector = (cell: CellItem) => cell.rowKey;
```

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagList/index.tsx
> +    ), [widget?.properties?.rows]);
Does not look right!

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagList/index.tsx
> +        const selectedMappingIndex = mapping?.findIndex((m) => {
Let's not use "single letter variable"

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagList/index.tsx
> +            const rowKey = sortedCells?.find((sc) => sc.subRowKey === cellKey)?.rowKey;
Let's not use "single letter variable"

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagList/index.tsx
> +        }) ?? false,
Let's not use "single letter variable"

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagList/index.tsx
> +            ?.rowLabel;
```suggestion
            .rowLabel;
```

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/ScaleTagInput/index.tsx
> +function ScaleTagInput(props: Props) {
Let's change the name. This doesn't not only handle Scale

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/ScaleTagInput/index.tsx
> +                && (m.widgetType === 'SCALE' || m.widgetType === 'SELECT' || m.widgetType === 'MULTISELECT')
Let us write a reusable function to check for these types

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +const widgetKeySelector = (n: Widget) => n.clientId;
Let's not use "single letter variable"

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +    const [mapping, setMapping] = useLocalStorage<MappingItem[] | undefined>(`mapping-${frameworkId}`, undefined);
Let's add a FIXME to remove this later

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +    const categoricalMapping = mapping?.filter(isCategoricalMapping);
Let's memoize this

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +                (om) => om.widgetPk === widgetPk,
Let's not use "double letter variable"

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +        value: !!mapping?.find((m) => m.widgetPk === widget.id && m.widgetType === 'NUMBER'),
Should not iterate inside renderer params

2022-02-23 10:54 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/TextToAssistItem/index.tsx
> +    textToAssist: string | undefined;
```suggestion
    text: string | undefined;
```

2022-02-23 10:54 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/TextToAssistItem/index.tsx
> +    onAssistedEntryAdd: ((newEntry: EntryInput) => void) | undefined;
This name is too specific

2022-02-23 10:54 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/TextToAssistItem/index.tsx
> +function TextToAssistItem(props: Props) {
```suggestion
function AssistItem(props: Props) {
```

2022-02-23 10:54 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/TextToAssistItem/index.tsx
> +    }
Let's do this outside the componenenenenenent

2022-02-23 10:54 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/SimplifiedTextView/index.tsx
> +    uniqueTextId: string;
```suggestion
    key: string;
```

2022-02-23 10:54 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/SimplifiedTextView/index.tsx
> +        ].filter(isDefined)
```suggestion
        ]
            .filter(isDefined)
```

2022-02-23 10:54 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/SimplifiedTextView/index.tsx
> +    } = useTextSelection(containerRef.current ?? undefined);
This doesn't look correct. Let's add a fixme

2022-02-23 10:54 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagList/index.tsx
> +import React, { useMemo, useCallback } from 'react';
Let's rename this file to Matrix1dTagInput

2022-02-24 05:06 UTC, priyesh777 approved these changes, later dismissed

2022-02-26 16:21 UTC, AdityaKhatri commented on app/views/AnalyticalFramework/AssistedTagging/CheckButton/index.tsx
> +    mappedCount?: number;
suggestions plz

2022-03-02 09:24 UTC, tnagorra requested changes

2022-03-02 09:24 UTC, tnagorra commented on app/components/framework/CompactAttributeInput/GeoLocationWidgetInput/index.tsx
> +    console.warn('Geo hints', widgetHints);
Let's remove this console.warn

2022-03-02 09:24 UTC, tnagorra commented on app/views/Project/EntryEdit/utils.ts
> +export function createDefaultAttributes(
Did we not have this function previously? Was this moved here?

2022-03-02 09:24 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/SimplifiedTextView/index.tsx
> +    // FIXME: Look into if the ref is working correctly
How do we do this check?

2022-03-02 09:24 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/CheckButton/index.tsx
> +    mappedCount?: number;
badgeCount, badgeText, badgeContent, badge?

2022-03-02 09:24 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagInput/index.tsx
> +        const selectedMappingsIndex = mappings?.findIndex((mapping) => {
The mappings is filtered a lot of times. We need to see if we can avoid these repetitions.

2022-03-02 09:24 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagInput/index.tsx
> +        }).length ?? 0,
Let's not do heavy computations on renderer params

2022-03-02 09:24 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagInput/index.tsx
> +    }, [sortedCells]);
Let's not do heavy computations on renderer params

2022-03-02 09:24 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +        mappedCount: categoricalMappings?.filter((m) => m.tagId === itemKey).length ?? 0,
Let's not do this computation here

2022-03-02 09:24 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +                description="Lorem Ipsum is simply dummy text of the printing and typesetting industry."
Do we have real text for description?

2022-03-02 09:24 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/index.tsx
> +const mockAssistedMappingsResponse = {
Let's add a FIXME comment to remove this mock data later on

2022-03-02 09:24 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/index.tsx
> +                if (mockAssistedMappingsResponse.numbers.length > 1) {
please use else if

2022-03-02 09:24 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/index.tsx
> +        filteredWidgets.forEach((widget) => {
I thought we were getting rid of forEach

2022-03-02 09:24 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/index.tsx
> +                };
Let's create a generic function to update existing features, add new features and delete features that are omitted

2022-03-02 11:56 UTC, AdityaKhatri commented on app/views/Project/EntryEdit/utils.ts
> +export function createDefaultAttributes(
Yes moved it here

2022-03-02 11:56 UTC, AdityaKhatri commented on app/views/Project/EntryEdit/LeftPane/SimplifiedTextView/index.tsx
> +    // FIXME: Look into if the ref is working correctly
Not sure

2022-03-03 02:44 UTC, AdityaKhatri commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagInput/index.tsx
> +    const mappingsByTagId = useMemo(() => (
rename

2022-03-03 02:46 UTC, AdityaKhatri commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/index.tsx
> +                    mappings={filteredMappings as Matrix1dMappingsItem[]}
might be undefined, cast properly

2022-03-03 02:46 UTC, AdityaKhatri commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +    const mappingsByTag = useMemo(() => (
rename

2022-03-03 02:49 UTC, AdityaKhatri commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/index.tsx
> +                        tempAttrs: [
user ternary operator

2022-03-03 02:50 UTC, AdityaKhatri commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/index.tsx
> +                        tempHints: hints ? [...oldTempHints, hintsWithInfo] : hints,
.

2022-03-03 02:52 UTC, AdityaKhatri commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/utils.ts
> +export function mergeLists<T>(
todo write tests

2022-03-03 02:54 UTC, AdityaKhatri commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/utils.ts
> +        ...updatedList,
reverse

2022-03-03 04:51 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/SimplifiedTextView/index.tsx
> +    // FIXME: Look into if the ref is working correctly
Why was the FIXME comment added?

2022-03-03 04:55 UTC, tnagorra commented on app/types/newAnalyticalFramework.ts
> +        subColumnKey?: string;
Where do we need this?

2022-03-03 04:56 UTC, tnagorra commented on app/utils/common.test.ts
> +    const oldList = [
This test does not handle removal of items or addition of new items.

2022-03-03 05:06 UTC, priyesh777 approved these changes, later dismissed

2022-03-03 05:14 UTC, AdityaKhatri commented on app/views/Project/EntryEdit/LeftPane/SimplifiedTextView/index.tsx
> +    // FIXME: Look into if the ref is working correctly
Because you said so

2022-03-03 05:25 UTC, tnagorra requested changes

2022-03-03 05:25 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix1dTagInput/index.tsx
> +            return false;
```suggestion
            return selectedTag === mapping.tagId && mapping.association.subRowKey === cellKey;
```

2022-03-03 05:25 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/SimplifiedTextView/index.tsx
> +
Let's just return if there is not assitedSplit

2022-03-03 05:25 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix2dTagInput/index.tsx
> +        });
We can simpify this

2022-03-03 05:25 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix2dTagInput/index.tsx
> +        });
this can be simplified

2022-03-03 05:25 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix2dTagInput/index.tsx
> +            return false;
This can be simplified

2022-03-03 05:25 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/OptionTypeTagInput/index.tsx
> +            return false;
This can be simplified

2022-03-03 05:25 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/index.tsx
> +                */
Let's remove these comments

2022-03-03 05:25 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/index.tsx
> +                };
Any reason this doesn't seem right?

2022-03-03 05:25 UTC, tnagorra commented on app/views/Project/EntryEdit/LeftPane/AssistPopup/utils.ts
> +        (subColumns) => subColumns.filter(isDefined),
Why do we need to filter subColumns? Is the col.association.subColumnKey not always defined?

2022-03-03 09:12 UTC, merged