Feature/terms check mark
the-deep/client pull request #2399
Opened 2022-03-04 09:06 UTC by priyesh777

## Changes:
- Add checkbox to accept terms and conditions in register section

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2022-03-04 09:17 UTC, AdityaKhatri requested changes

2022-03-04 09:17 UTC, AdityaKhatri commented on app/views/Register/RegisterForm/index.tsx
> +        showTermsModal, ,
```suggestion
        isTermsModalShown, ,
```

2022-03-04 09:17 UTC, AdityaKhatri commented on app/views/Register/RegisterForm/index.tsx
> +    }, [acceptTerms]);
not needed

2022-03-04 09:17 UTC, AdityaKhatri commented on app/views/Register/RegisterForm/index.tsx
> +                            </Button>
change order

2022-03-04 10:56 UTC, tnagorra requested changes

2022-03-04 10:56 UTC, tnagorra commented on app/views/Register/RegisterForm/index.tsx
> +    const [acceptTerms, setAcceptTerms] = useState(false);
```suggestion
    const [termsAccepted, setTermsAffected] = useState(false);
```

2022-03-04 10:56 UTC, tnagorra commented on app/views/Register/RegisterForm/index.tsx
> +        isTermsModalHidden, ,
```suggestion
        setTermsModalHidden, ,
```

2022-03-07 04:59 UTC, priyesh777 commented on app/views/Register/RegisterForm/index.tsx
> +    const [acceptTerms, setAcceptTerms] = useState(false);
I hope that means "setTermsAccepted"

2022-03-08 03:11 UTC, merged