Feature/connector stats
the-deep/client pull request #2407
Opened 2022-03-07 01:37 UTC by AdityaKhatri

## Changes

* Add connector stats
* Add filter

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2022-03-07 05:24 UTC, barshathakuri submitted a review, later dismissed

2022-03-08 10:00 UTC, tnagorra requested changes

2022-03-08 10:00 UTC, tnagorra commented on app/views/ProjectEdit/Connector/ConnectorDetail/index.tsx
> +                    }
Why not get all edit information here and instead trigger a refetch?

2022-03-08 10:00 UTC, tnagorra commented on app/views/ProjectEdit/Connector/ConnectorDetail/index.tsx
> +    ), [connector]);
Do we want to disable retrigger if "some source is processing" or "all are processing"?
@AdityaKhatri @thenav56

2022-03-08 10:49 UTC, merged