Fix/usergroup query
the-deep/client pull request #2411
Opened 2022-03-10 02:04 UTC by priyesh777

## Changes:
- Replace REST endpoints with GQL endpoints and also remove email field from user table

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2022-03-10 05:29 UTC, AdityaKhatri requested changes

2022-03-10 05:29 UTC, AdityaKhatri commented on app/views/ProjectEdit/Users/index.tsx
> +    );
Also handle pagination

2022-03-10 05:29 UTC, AdityaKhatri commented on app/views/UserGroup/AddUsergroupModal/index.tsx
> +                const data = { ...val } as FormType;
```suggestion
                const data = val as FormType;
```

2022-04-06 10:24 UTC, tnagorra requested changes

2022-04-06 10:24 UTC, tnagorra commented on app/views/UserGroup/index.tsx
> +            ?.results?.find((a: UsersGroupType) => a.id === userGroupToEdit)
```suggestion
            ?.results?.find((userGroup) => userGroup.id === userGroupToEdit)
```

2022-04-06 10:24 UTC, tnagorra commented on app/views/UserGroup/index.tsx
> +            },
onCompleted doesn't always mean success. We should check if `ok` is `true`

2022-04-06 10:24 UTC, tnagorra commented on app/views/UserGroup/index.tsx
> +    ] = useMutation<UserGroupDeleteMutation, UserGroupDeleteMutationVariables>(
Let us also use loading to block actions when delete is in progress

2022-04-06 10:24 UTC, tnagorra commented on app/views/UserGroup/index.tsx
> +                }
Do we need a result when we are deleting userGroup?

2022-04-06 10:24 UTC, tnagorra commented on app/views/ProjectEdit/Users/index.tsx
> +        project(id: $id) {
Please fix the indentation

2022-04-06 10:24 UTC, tnagorra commented on app/views/UserGroup/AddUsergroupModal/index.tsx
> +                onModalClose();
We should try to not call too many callbacks.

Also, we are not handling the case when error occurs.

2022-04-06 10:24 UTC, tnagorra commented on app/views/UserGroup/AddUsergroupModal/index.tsx
> +                onModalClose();
We should try to not call too many callbacks.

Also, we are not handling the case when error occurs.

2022-04-06 10:24 UTC, tnagorra commented on app/views/UserGroup/UserGroupItem/AddUserModal/index.tsx
> +        ) {
Indentation is not correct.

2022-04-06 10:24 UTC, tnagorra commented on app/views/UserGroup/UserGroupItem/index.tsx
> +            }
Indentation is not correct.

2022-04-06 10:24 UTC, tnagorra commented on app/views/UserGroup/UserGroupItem/index.tsx
> +                    role
Indentation is not correct.

2022-04-08 10:35 UTC, merged