Remove entry comment local state
the-deep/client pull request #2433
Opened 2022-04-11 06:41 UTC by samshara

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2022-04-11 10:44 UTC, tnagorra requested changes

2022-04-11 10:44 UTC, tnagorra commented on app/components/entryReview/EntryComments/Comment/index.tsx
> +        isEditModeVisible,
Let's just rename this to `editViewShown`

2022-04-11 10:44 UTC, tnagorra commented on app/components/entryReview/EntryComments/Comment/index.tsx
> +                            onCloseEditView={hideEditView}
```suggestion
                            onClose={hideEditView}
```

2022-04-13 05:13 UTC, subinasr approved these changes

2022-04-13 05:21 UTC, tnagorra approved these changes

2022-04-13 05:31 UTC, merged