Add Analysis Route
the-deep/client pull request #2467
Opened 2022-05-09 11:03 UTC by barshathakuri

- Addresses XXX
- Depends on XXX

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2022-05-10 09:36 UTC, AdityaKhatri approved these changes, later dismissed

2022-05-12 03:52 UTC, AdityaKhatri requested changes

2022-05-12 03:52 UTC, AdityaKhatri commented on app/views/Project/AnalysisModule/Analysis/index.tsx
> +                        title={_ts('analysis', 'cloneAnalysisButtonTitle')}
Change title to 'Export'

2022-05-12 03:52 UTC, AdityaKhatri commented on app/views/Project/AnalysisModule/Analysis/index.tsx
> +                        name="clone"
```suggestion
                        name={undefined}
```

2022-05-12 03:52 UTC, AdityaKhatri commented on app/views/Project/AnalysisModule/Analysis/index.tsx
> +                        onClick={hideCreateNewExportModal}
handle this properly

2022-05-12 03:52 UTC, AdityaKhatri commented on app/views/Project/AnalysisModule/Export/index.tsx
> +        >
Tabs is not required.

2022-05-12 03:52 UTC, AdityaKhatri commented on app/views/Project/AnalysisModule/Export/index.tsx
> +    const [activeTab, setActiveTab] = useState<ExportType | undefined>('export-entry-history');
Tabs is not required.

2022-05-15 12:00 UTC, AdityaKhatri commented
@barshathakuri , check for linting and typecheck issues.
Fix deepscan issues.

2022-05-17 06:05 UTC, samshara commented on app/Base/configs/routes.tsx
> +    path: '/analysis-module/',
have we decided to use this path?

2022-05-20 05:23 UTC, AdityaKhatri approved these changes

2022-05-20 05:55 UTC, merged