Feature/project clusters
the-deep/client pull request #2522
Opened 2022-06-13 09:52 UTC by AdityaKhatri

## Changes

* Show project clusters

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2022-06-17 04:08 UTC, tnagorra requested changes

2022-06-17 04:08 UTC, tnagorra commented on app/views/ExploreDeep/MapView/index.tsx
> +        } = markerProps as { project_ids: string | undefined };
```suggestion
        } = markerProps as ClusterProperties;
```

Shouldn't this just be ClusterProperties?

2022-06-17 04:08 UTC, tnagorra commented on app/views/ExploreDeep/MapView/index.tsx
> +            projectIds?.split(',')?.filter((id) => id.length > 0) ?? [],
```suggestion
            projectIds?.split(',').filter((id) => id.length > 0) ?? [],
```

2022-06-17 04:08 UTC, tnagorra commented on app/views/ExploreDeep/MapView/index.tsx
> +        const width = Math.min(8 * Math.log10(uniqueProjectsCount) + 20, 100);
Let's check if uniqueProjectsCount is zero by any chance

2022-06-17 04:08 UTC, tnagorra commented on app/views/ExploreDeep/PublicMapView/index.tsx
> +    const createClusterMarker = useCallback((markerProps: object) => {
Why are we repeating this map view?

2022-06-17 04:08 UTC, tnagorra commented on app/views/ExploreDeep/PublicMapView/index.tsx
> +    const createClusterMarker = useCallback((markerProps: object) => {
The map should be re-used with the fetching logic separated out.

2022-06-17 09:44 UTC, subinasr approved these changes

2022-06-20 08:59 UTC, subinasr approved these changes

2022-06-20 09:36 UTC, tnagorra requested changes, later dismissed

2022-06-20 09:36 UTC, tnagorra commented on app/views/ExploreDeep/ProjectCountMap/index.tsx
> +            }
Shouldn't the second if also be on if-else chain?

2022-06-20 09:36 UTC, tnagorra commented on app/views/ExploreDeep/ProjectCountMap/index.tsx
> +                                .filter(isDefined);
Shouldn't we also take a unique count here?

2022-06-20 09:36 UTC, tnagorra commented on app/views/ExploreDeep/ProjectCountMap/index.tsx
> +                    projectId: project,
Why set id and projectId as the same value?

2022-06-20 09:38 UTC, AdityaKhatri commented on app/views/ExploreDeep/ProjectCountMap/index.tsx
> +                    projectId: project,
Sir already there

2022-06-20 09:38 UTC, AdityaKhatri commented on app/views/ExploreDeep/ProjectCountMap/index.tsx
> +                                .filter(isDefined);
Sir already there

2022-06-20 09:38 UTC, AdityaKhatri commented on app/views/ExploreDeep/ProjectCountMap/index.tsx
> +            }
Sir already there

2022-06-21 08:18 UTC, merged