Fetch recent activities from graphql
the-deep/client pull request #2523
Opened 2022-06-15 08:55 UTC by subinasr

- Addresses #2512 

## Changes

* Use graphql to fetch recent activities

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2022-06-17 04:12 UTC, tnagorra approved these changes

2022-06-19 09:04 UTC, AdityaKhatri commented on app/views/Home/RecentActivity/ActivityItem/index.tsx
> +                                leadId: '1',
Lets use the actual leadId

2022-06-19 09:04 UTC, AdityaKhatri commented on app/views/Home/RecentActivity/ActivityItem/index.tsx
> +                leadId: activity?.leadId ?? '1',
If there is no leadId, lets not make it a link

2022-06-19 09:05 UTC, AdityaKhatri commented on app/views/Home/RecentActivity/ActivityItem/index.tsx
> +                     || (activity?.type === 'ENTRY_COMMENT')) && activity?.leadId,
I think this should be entyId

2022-06-19 09:05 UTC, AdityaKhatri commented on app/views/Home/RecentActivity/ActivityItem/index.tsx
> +                                leadId: '1',
Also, send the user to #primary-tagging

2022-06-19 09:05 UTC, AdityaKhatri commented on app/views/Home/RecentActivity/ActivityItem/index.tsx
> +                                entryId: '1',
Lets use real entry and leadIds

2022-06-19 09:06 UTC, AdityaKhatri requested changes
Fix comments

2022-06-23 06:51 UTC, merged