Add auto-match in assisted tagging
the-deep/client pull request #2544
Opened 2022-07-11 05:17 UTC by AdityaKhatri

- Addresses XXX
- Depends on XXX

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2022-07-11 05:22 UTC, samshara commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +            console.warn('here', item.label, predictionTagsMapByName);
remove console.warn() here.

2022-07-11 05:28 UTC, samshara commented on app/views/AnalyticalFramework/AssistedTagging/utils.ts
> +    ];
any reason why we aren't mapping `rows` here?

2022-07-25 08:00 UTC, samshara approved these changes

2022-07-29 04:08 UTC, tnagorra requested changes

2022-07-29 04:08 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +                            variant="tertiary"
Don't we need to disable this when `pending`?

2022-07-29 04:08 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +            if (tagId) {
When will we not have tagId? When af changes?

2022-07-29 04:08 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/utils.test.ts
> +const matrix2dPossibleMapping = [
Let's define the type for possible mapping

2022-07-29 04:22 UTC, tnagorra approved these changes

2022-07-29 04:22 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/utils.test.ts
> +});
Let's add tests for other widgets as well.

2022-08-05 04:23 UTC, tnagorra requested changes

2022-08-05 04:23 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +        )).filter(isDefined).flat();
Pikachu!!

2022-08-05 04:23 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/index.tsx
> +                            variant="tertiary"
Bulbasaur!

2022-08-05 04:23 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/utils.test.ts
> +                        label: 'sub-row-1-1',
Charizard!

2022-08-05 04:23 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/utils.test.ts
> +                color: '',
Dragonite!

2022-08-05 04:23 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/utils.ts
> +type Possible<T> = Omit<T, 'tag' | 'clientId' | 'id'> & { label: string };
Squirtle!

2022-08-05 04:23 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/utils.ts
> +    ] as Matrix2dPossibleMapping[];
Slowpoke!

2022-08-05 08:38 UTC, tnagorra approved these changes

2022-08-05 10:47 UTC, subinasr approved these changes

2022-08-05 11:22 UTC, merged