Add user delete functionality
the-deep/client pull request #2549
Opened 2022-07-21 09:31 UTC by AdityaKhatri

depends on https://github.com/the-deep/server/pull/1118

## Changes

* Add the ability to delete user

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2022-07-22 06:14 UTC, subinasr requested changes

2022-07-22 06:14 UTC, subinasr commented on app/views/MyProfile/styles.css
> +                }
I see both 'cancel' and the 'delete user' button is assigned the same classname. Are you sure both buttons should appear the same? Or is this a mistake?

2022-07-22 06:14 UTC, subinasr commented on app/components/selections/ProjectUserSelectInput/index.tsx
> +
Can you tell me why you've assigned a type like this instead of using the type from graphql itself?

2022-07-25 04:23 UTC, AdityaKhatri commented on app/views/MyProfile/styles.css
> +                }
This has been fixed.

2022-07-25 04:26 UTC, AdityaKhatri commented on app/components/selections/ProjectUserSelectInput/index.tsx
> +
Yeah, while we can infer from the type, we were using this type outside as well and we were transforming items. The types exactly didn't match.

2022-07-25 08:52 UTC, subinasr approved these changes

2022-07-25 08:52 UTC, subinasr commented on app/components/selections/ProjectUserSelectInput/index.tsx
> +
I don't understand. We can still export the types and shouldn't it still match?

2022-07-25 11:04 UTC, merged