Add list of sole projects
the-deep/client pull request #2551
Opened 2022-07-28 09:18 UTC by AdityaKhatri

## Changes

* List sole users before user deletion

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2022-07-28 10:04 UTC, tnagorra requested changes

2022-07-28 10:04 UTC, tnagorra commented on app/views/MyProfile/UserDeleteConfirmModal/index.tsx
> +    onDeleteAccountModalCloseClick: () => void;
```suggestion
    onClose: () => void;
```

2022-07-28 10:04 UTC, tnagorra commented on app/views/MyProfile/UserDeleteConfirmModal/index.tsx
> +                        disabled={(soleProjects?.length ?? 0) > 0}
Let's also disable this when pending

2022-07-28 10:38 UTC, tnagorra approved these changes

2022-08-01 06:24 UTC, subinasr approved these changes

2022-08-01 06:38 UTC, merged