Feature/framework mapping update
the-deep/client pull request #2614
Opened 2023-02-02 13:15 UTC by AdityaKhatri

## Changes

* Add new framework mapping flow

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2023-02-06 05:18 UTC, tnagorra requested changes

2023-02-06 05:18 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/FrameworkTagRow/AddButton/index.tsx
> +function AddButton(props: Props) {
We could have a more specific name

2023-02-06 05:18 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/FrameworkTagRow/AddButton/index.tsx
> +        onTagSelect(newTag);
Let's invert the order.

2023-02-06 05:18 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix2dTagInput/index.tsx
> +        if (isDefined(selectedMappingsIndex) && selectedMappingsIndex !== -1) {
It is a bit weird to check if selectedMappingsIndex is defined or not.

2023-02-06 05:18 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix2dTagInput/index.tsx
> +        if (isDefined(selectedMappingsIndex) && selectedMappingsIndex !== -1) {
It is a bit weird to check if selectedMappingsIndex is defined or not.

2023-02-06 05:18 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/Matrix2dTagInput/index.tsx
> +        if (isDefined(selectedMappingsIndex) && selectedMappingsIndex !== -1) {
It is a bit weird to check if selectedMappingsIndex is defined or not.

2023-02-06 05:18 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/OptionTypeTagInput/index.tsx
> +        if (isDefined(selectedMappingsIndex) && selectedMappingsIndex !== -1) {
It is a bit weird to check if selectedMappingsIndex is defined or not.

2023-02-06 05:18 UTC, tnagorra commented on app/views/AnalyticalFramework/AssistedTagging/WidgetTagList/OrganigramTagInput/index.tsx
> +        if (isDefined(selectedMappingsIndex) && selectedMappingsIndex !== -1) {
It is a bit weird to check if selectedMappingsIndex is defined or not.

2023-02-09 06:10 UTC, samshara approved these changes

2023-02-09 06:45 UTC, tnagorra approved these changes

2023-02-09 06:56 UTC, merged