Add intensity slider in heatmap
the-deep/client pull request #2615
Opened 2023-02-09 11:05 UTC by AdityaKhatri

## Changes

* Add intensity slider in heatmap

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2023-02-09 11:31 UTC, samshara commented on app/components/input/SliderInput/index.tsx
> +            // index={index}
let's remove this

2023-02-09 11:31 UTC, samshara commented on app/components/input/SliderInput/index.tsx
> +    );
we could memoise this

2023-02-14 06:16 UTC, tnagorra requested changes

2023-02-14 06:16 UTC, tnagorra commented on app/views/NewExploreDeep/EntriesContent/EntriesHeatMap/styles.css
> +    background-color: rgba(255, 255, 255, 0.6);
Let's use css variables

2023-02-14 06:16 UTC, tnagorra commented on app/views/NewExploreDeep/index.tsx
> +            skip: printPreviewMode ? false : (activeView !== 'entries'),
```suggestion
            skip: !printPreviewMode && activeView !== 'entries',
```

2023-02-14 06:16 UTC, tnagorra commented on app/views/NewExploreDeep/index.tsx
> +            skip: printPreviewMode ? false : (activeView !== 'projects'),
```suggestion
            skip: !printPreviewMode && activeView !== 'projects',
```

2023-02-14 06:16 UTC, tnagorra commented on app/views/NewExploreDeep/index.tsx
> +            skip: printPreviewMode ? false : (activeView !== 'entries'),
```suggestion
            skip: !printPreviewMode && activeView !== 'entries',
```

2023-02-15 05:53 UTC, tnagorra approved these changes

2023-02-15 05:55 UTC, merged