Feature/separate explore deep content
the-deep/client pull request #2616
Opened 2023-02-21 10:11 UTC by AdityaKhatri

## Changes

* Separate explore deep content

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2023-02-27 09:06 UTC, tnagorra requested changes

2023-02-27 09:06 UTC, tnagorra commented on app/views/ExploreDeepContent/BrushLineChart.tsx
> +
Let's remove console :D

2023-02-27 09:06 UTC, tnagorra commented on app/Base/configs/env.ts
> +export const staticEndpoint = process.env.REACT_APP_STATIC_ENDPOINT as string; // http://localhost:8000/graphql
```suggestion
export const staticEndpoint = process.env.REACT_APP_STATIC_ENDPOINT as string;
```

2023-02-27 09:06 UTC, tnagorra commented on app/views/PublicExploreDeep/index.tsx
> +    );
```suggestion
    const [
        startDate = deepStartDateTime,
        setStartDate,
    ] = useState<number | undefined>(
        lastYearDateTime,
    );
    const [
        endDate = todaysDateTime,
        setEndDate,
    ] = useState<number | undefined>(
        todaysDateTime,
    );
```

2023-02-27 09:06 UTC, tnagorra commented on app/views/PublicExploreDeep/index.tsx
> +                    }
Isn't this supposed to be setEndDate(Math.min(yearEndDate, endDate))

2023-02-27 09:06 UTC, tnagorra commented on app/views/PublicExploreDeep/index.tsx
> +    const onSnapshotChange = useCallback((newSnapshotId: string) => {
```suggestion
    const handleSnapshotChange = useCallback((newSnapshotId: string) => {
```

2023-02-27 09:06 UTC, tnagorra commented on app/views/ExploreDeepContent/index.tsx
> +                            />
We can re-use these

2023-02-27 09:06 UTC, tnagorra commented on app/views/ExploreDeepContent/index.tsx
> +                            />
We can re-use these

2023-02-28 08:56 UTC, AdityaKhatri commented on app/views/ExploreDeepContent/BrushLineChart.tsx
> +
@tnagorra , lets remove console :D
![image](https://user-images.githubusercontent.com/7893887/221802798-c4ad94b7-ab21-4f89-bbfa-6755eee42c0c.png)

2023-03-01 05:33 UTC, tnagorra commented on app/views/ExploreDeepContent/BrushLineChart.tsx
> +
Yes.

2023-03-01 09:24 UTC, tnagorra requested changes

2023-03-01 09:24 UTC, tnagorra commented on app/views/ExploreDeepContent/BrushLineChart.tsx
> +                // FIXME: this should be unset on public dashboard
Please check for maxDomain.
For public dashboard (for a year), the minDomain and maxDomain should be the first second of the year and the last second of the year respectively.

2023-03-01 09:24 UTC, tnagorra commented on app/views/PublicExploreDeep/index.tsx
> +                    setEndDate(Math.min(yearEndDate, endDate));
If we are reading startDate and endDate from `                    response.publicDeepExploreYearlySnapshots`, shouldn't we also get maximum comparing those values

2023-03-01 09:24 UTC, tnagorra commented on app/views/ExploreDeepContent/index.tsx
> +    //
```suggestion

```

2023-03-01 09:24 UTC, tnagorra commented on app/views/ExploreDeepContent/index.tsx
> +    ]);
Why separate out the props? Why not directly define variables for ProjectContent and PEntriesContent component

2023-03-02 05:25 UTC, AdityaKhatri commented on app/views/ExploreDeepContent/BrushLineChart.tsx
> +                // FIXME: this should be unset on public dashboard
I think this is fine.

2023-03-02 06:20 UTC, tnagorra approved these changes

2023-03-02 06:22 UTC, merged