Feature/setup ary dashboard
the-deep/client pull request #2705
Opened 2023-07-18 09:07 UTC by AdityaKhatri

## Changes

* Setup ary dashboard

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2023-07-18 09:18 UTC, shreeyash07 requested changes

2023-07-18 09:18 UTC, shreeyash07 commented on app/views/AryDashboard/Statistics/index.tsx
> +    console.warn('here', projectId);
remove console

2023-07-18 09:18 UTC, shreeyash07 commented on app/views/AryDashboard/Statistics/index.tsx
> +
Add note if these are dummy data

2023-08-24 09:42 UTC, puranban approved these changes

2023-08-24 09:58 UTC, shreeyash07 approved these changes

2023-08-24 10:04 UTC, merged