Assessment Registry - Methodology
the-deep/client pull request #2707
Opened 2023-07-20 09:06 UTC by shreeyash07

- Addresses #2706 
- Depends on [fix/executive-summary](https://github.com/the-deep/server/pull/1332)

## Changes

* Add methodlogy tab

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

2023-07-20 09:17 UTC, AdityaKhatri requested changes

2023-07-20 09:17 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/MethodologyAttributesForm/index.tsx
> +    value: MethodologyAttributesType,
```suggestion
    value: MethodologyAttributesType;
```

2023-07-20 09:17 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/MethodologyAttributesForm/index.tsx
> +                    label="SAMPLING SIZE"
Capitalize all labels

2023-07-20 09:17 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/index.tsx
> +                Methodlogy content
```suggestion
                Methodlogy
```

2023-07-20 09:17 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/index.tsx
> +            ))}
need to add key

2023-07-20 09:33 UTC, AdityaKhatri approved these changes, later dismissed

2023-07-20 09:41 UTC, tnagorra requested changes

2023-07-20 09:41 UTC, tnagorra commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/index.tsx
> +                <MethodologyAttributesForm
```suggestion
                <MethodologyAttributesInput
```

2023-07-20 09:41 UTC, tnagorra commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/index.tsx
> +                </QuickActionButton>
Let's add title when we are using icon button

2023-07-20 09:41 UTC, tnagorra commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/index.tsx
> +        error: riskyError,
Let's pass disabled and readonly prop to all forms

2023-07-20 09:41 UTC, tnagorra commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/MethodologyAttributesForm/index.tsx
> +            </QuickActionButton>
Let's add title for icon button

2023-07-20 09:41 UTC, tnagorra commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/MethodologyAttributesForm/index.tsx
> +    );
Let's move this to parent so that it's only called twice.

2023-07-20 09:41 UTC, tnagorra commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/MethodologyAttributesForm/index.tsx
> +};
```suggestion
const defaultMethodologyAttributeValue = (): MethodologyAttributesType => ({
    clientId: randomString(),
});
```

2023-07-24 10:25 UTC, AdityaKhatri submitted a review, later dismissed

2023-07-25 05:26 UTC, puranban approved these changes, later dismissed

2023-07-25 05:34 UTC, tnagorra requested changes

2023-07-25 05:34 UTC, tnagorra commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/MethodologyAttributesInput/index.tsx
> +    readonly?: boolean;
```suggestion
    readOnly?: boolean;
```

2023-07-25 05:34 UTC, tnagorra commented on app/views/EditAry/AssessmentRegistryForm/MethodologyForm/index.tsx
> +                const newOldValue = oldValue ?? [];
```suggestion
                const safeOldValue = oldValue ?? [];
```

2023-07-25 08:24 UTC, tnagorra approved these changes

2023-07-25 08:24 UTC, merged