Assessment Registry - Score form
the-deep/client pull request #2724
Opened 2023-08-04 09:31 UTC by shreeyash07

- Addresses #2723 
- Depends on [feature/summary-score-cna](https://github.com/the-deep/server/pull/1324)

## Changes

* Add score form

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2023-08-04 10:50 UTC, AdityaKhatri requested changes
Also update scoreRating formSchema.

2023-08-04 10:50 UTC, AdityaKhatri commented on app/gqlFragments.ts
> +            scoreType
id might be required, check with @Rup-Narayan-Rajbanshi

2023-08-04 10:50 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/AnalyticalDensityForm/index.tsx
> +    );
use useMemo

2023-08-10 04:33 UTC, AdityaKhatri requested changes

2023-08-10 04:33 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/AnalyticalDensityForm/AnalyticalDensityInput/index.tsx
> +    ]), [options]);
useMemo is not required here.

2023-08-10 04:33 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/AnalyticalDensityForm/index.tsx
> +            </div>
Use Message component

2023-08-10 04:33 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/AnalyticalDensityForm/index.tsx
> +                    : undefined;
use ListVIew

2023-08-10 04:33 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/QualityScoreForm/index.tsx
> +    );
use useMemo

2023-08-10 04:33 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/QualityScoreForm/index.tsx
> +            <ListView
double nesting not required

2023-08-10 04:33 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/index.tsx
> +    );
move this inside the useMemo below

2023-08-10 04:33 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/index.tsx
> +            score: median(sectorWiseDensityValue ?? []) ?? 0,
```suggestion
            score: median(sectorWiseDensityValue ?? []),
```

2023-08-10 04:33 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/index.tsx
> +
fix sorting

2023-08-10 04:33 UTC, AdityaKhatri commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/index.tsx
> +                ))}
use ListView

2023-08-10 04:59 UTC, shreeyash07 commented on app/views/EditAry/AssessmentRegistryForm/ScoreForm/index.tsx
> +            score: median(sectorWiseDensityValue ?? []) ?? 0,
Not possible median returns undefined if array length is >= 0

2023-08-10 08:05 UTC, AdityaKhatri submitted a review, later dismissed

2023-08-10 10:38 UTC, merged