Feature/report builder
the-deep/client pull request #2745
Opened 2023-09-01 05:25 UTC by AdityaKhatri

## Changes

* Create report builder

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2023-09-27 18:00 UTC, tnagorra requested changes, later dismissed

2023-09-27 18:00 UTC, tnagorra commented on app/Base/configs/routes.tsx
> +    path: '/reports/:reportSlug/',
The reportEditRoute and publicReportViewRoute only differ on the type of the url param type. Let's have completely separate urls.

2023-09-27 18:00 UTC, tnagorra commented on app/components/Portal/index.tsx
> +        children,
Let's add a NOTE why we are not using Portal from deep-ui

2023-09-27 18:00 UTC, tnagorra commented on app/views/PublicReportView/index.tsx
> +    } = useQuery<PublicReportSnapshotQuery, PublicReportSnapshotQueryVariables>(
Let's handle error and pending states.

2023-09-27 18:00 UTC, tnagorra commented on app/views/PublicReportView/index.tsx
> +    } = useQuery<PublicReportDetailsQuery, PublicReportDetailsQueryVariables>(
Let's handle error and pending states.

2023-09-27 18:00 UTC, tnagorra commented on app/views/AnalysisDashboard/ReportsModal/index.tsx
> +                    }
Don't we have id on latestSnapshot?

2023-09-27 18:00 UTC, tnagorra commented on app/views/PublicReportView/index.tsx
> +        }
Do we not have id for file and reportDataFile?

2023-09-27 18:00 UTC, tnagorra commented on app/components/GalleryFileUpload/index.tsx
> +                }
Don't we have id for file?

2023-09-27 18:00 UTC, tnagorra commented on app/components/GalleryFileUpload/index.tsx
> +        </FileInput>
Let's add title

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/FileUpload/index.tsx
> +    }
Let's check if we have missed `id` in these query objects

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/MetadataEdit/index.tsx
> +            <TextInput
Don't we need a NonFieldError?

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/BackgroundEdit/index.tsx
> +                <NumberInput
Let's add NonFieldError

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/BorderEdit/index.tsx
> +                <ColorInput
Let's add NonFieldError

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/ContainerStylesEdit/index.tsx
> +            <BorderEdit
Let's add NonFieldError

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/Content/index.tsx
> +        configuration: configurationFromProps = {},
```suggestion
        configuration: configurationFromProps,
```

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/Content/index.tsx
> +            } = {},
```suggestion
            },
```

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/Content/index.tsx
> +                    {content ?? 'Title goes here'}
```suggestion
                    {content || 'Title goes here'}
```
We might need to think about empty string

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/Content/index.tsx
> +            } = {},
```suggestion
            },
```

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/Content/index.tsx
> +            } = {},
```suggestion
            },
```

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/Content/index.tsx
> +            } = {},
```suggestion
            },
```

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/Content/index.tsx
> +        }
Let's also have a fallback preview for image here

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/HeadingEdit/index.tsx
> +                    label="Heading"
Let's add NonFieldError

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/ImageEdit/index.tsx
> +                    disabled={disabled}
Let's add NonFieldError

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/PaddingEdit/index.tsx
> +                    name="top"
Let's add NonFieldError

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/TextEdit/index.tsx
> +                contentClassName={styles.expandedBody}
Let's add NonFieldError

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/TextElementsStylesEdit/index.tsx
> +                    value={value?.size}
Let's add NonFieldError

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/UrlEdit/index.tsx
> +                    error={error?.url}
Let's add NonFieldError

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/index.tsx
> +    const [containerToEdit, setContainerToEdit] = useState<string>();
```suggestion
    const [containerToEdit, setContainerToEdit] = useState<string | undefined>();
```

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/index.tsx
> +                    )}
Let's add title

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/index.tsx
> +                <NonFieldError error={getErrorObject(error)?.containers} />
Let's add NonFieldError for the root

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/index.tsx
> +                        heading="Metadata Edit"
```suggestion
                        heading="Edit Metadata"
```

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/styles.css
> +        overflow-y: auto;
Are we hard-coding these values?

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/Toc/index.tsx
> +    ]);
The containerIdForLabel might not always be unique.

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/Toc/index.tsx
> +                    </Button>
Let's add title

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/schema.ts
> +)
Let's add a comment why we are adding these types here.

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/utils.ts
> +    } = generalContainerStyle ?? {};
```suggestion
    if (!containerStyle && !generalContainerStyle) {
        return {};
    }

    const {
        padding,
        border,
        background,
    } = containerStyle;

    const {
        padding: generalPadding,
        border: generalBorder,
        background: generalBackground,
    } = generalContainerStyle;
```

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/utils.ts
> +    } = generalTextStyle ?? {};
```suggestion
    } = textStyle;

    const {
        align: generalAlign,
        color: generalColor,
        family: generalFamily,
        weight: generalWeight,
        size: generalSize,
    } = generalTextStyle;
```

2023-09-27 18:00 UTC, tnagorra commented on app/gqlFragments.ts
> +            }
Let's check if we need to fetch `id`

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/index.tsx
> +}
We might need to type the return type strictly.

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/index.tsx
> +    const index = allItems?.findIndex((item) => item.clientId === containerKey);
Let's memoize this.

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/index.tsx
> +    ), [totalColSpan, width]);
Let's add a NOTE here

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/index.tsx
> +}
We can also optimize the re-order function by not editing the object if the new order is equal to old order

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/index.tsx
> +            }));
Let's add comment here.

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/index.tsx
> +            }));
Let's add comment here.

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/index.tsx
> +        return configuration?.heading?.content?.replace(' ', '-');
Why are replacing space with dash?

2023-09-27 18:00 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/index.tsx
> +                        />
Don't we need to pass error here?

2023-09-27 18:00 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +            }
Let's check if we need to fetch `id` here

2023-09-27 18:00 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +                            row: acc.length + 1 + statementIndex + 1,
How does this work?

2023-09-27 18:00 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +                                        statement.reportText,
Don't we need to check if we have content for statement, informationGaps and reportText?

2023-09-27 18:00 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +                }] as ReportContainerType[]);
We should not cast the type here.

2023-09-27 18:00 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +                const uploadItems = valueToSet.containers?.map((item) => item.contentData).flat();
We can also directly use flatMap

2023-09-27 18:00 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +    ] = useState(false);
Let's move this to the top.

2023-09-27 18:00 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +            'Are you sure you want to published the report?'
```suggestion
            'Are you sure you want to publish the report?'
```

2023-09-27 18:00 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +            Are you sure you want to published the report?`
```suggestion
            Are you sure you want to publish the report?`
```

2023-09-27 18:00 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +                        </Button>
Let's also disable the button when we are doing any action.

2023-09-27 18:00 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +                        disabled={false}
We should also disable the report builder while we are waiting for the mutation

2023-09-28 06:33 UTC, AdityaKhatri commented on app/views/PublicReportView/index.tsx
> +        }
no

2023-09-28 06:33 UTC, AdityaKhatri commented on app/components/GalleryFileUpload/index.tsx
> +                }
no

2023-09-28 06:35 UTC, AdityaKhatri commented on app/components/report/ReportBuilder/FileUpload/index.tsx
> +    }
its all good

2023-09-28 06:45 UTC, AdityaKhatri commented on app/components/report/ReportBuilder/index.tsx
> +    const [containerToEdit, setContainerToEdit] = useState<string>();
auto inferred

2023-09-28 06:47 UTC, AdityaKhatri commented on app/components/report/ReportBuilder/styles.css
> +        overflow-y: auto;
somewhat yes

2023-09-28 06:48 UTC, AdityaKhatri commented on app/components/report/Toc/index.tsx
> +    ]);
yes, and I think thats fine, we cannot really fix this without adding other indicators

2023-09-28 06:51 UTC, AdityaKhatri commented on app/components/report/utils.ts
> +    } = generalContainerStyle ?? {};
Fixed in a weird way, type is not auto inferred.

2023-09-28 07:03 UTC, AdityaKhatri commented on app/views/ReportEdit/index.tsx
> +                            row: acc.length + 1 + statementIndex + 1,
Each pillar will add one header row and multiple statement rows. The loop of reduce will treat one pillar at a time.

2023-09-28 07:14 UTC, AdityaKhatri commented on app/views/ReportEdit/index.tsx
> +                        </Button>
The actions are saved immediately to form so shouldn't pose any issues.

2023-09-28 07:53 UTC, tnagorra commented on app/components/report/ReportBuilder/ReportContainer/Content/index.tsx
> +        }
Is this added?

2023-09-28 07:53 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +                        </Button>
Don't we still send a request to server?

2023-09-28 07:55 UTC, tnagorra commented on app/components/report/Toc/index.tsx
> +    ]);
What do you mean by indicators?

2023-09-28 07:55 UTC, tnagorra commented on app/components/report/utils.ts
> +    } = generalContainerStyle ?? {};
Why wouldn't it be inferred?

2023-09-28 07:56 UTC, tnagorra commented on app/views/ReportEdit/index.tsx
> +                            row: acc.length + 1 + statementIndex + 1,
How does this math work? Still not very clear. We need to add NOTE on how this works.

2023-09-28 11:16 UTC, barshathakuri approved these changes, later dismissed

2023-09-28 11:16 UTC, barshathakuri commented on app/components/report/ReportBuilder/ReportContainer/styles.css
> +        width: 100%;
Is this a useful code?

2023-09-28 11:16 UTC, barshathakuri commented on app/translate/index.tsx
>  import devLang from './dev-lang.json';
```suggestion
import { isDefined } from '@togglecorp/fujs';

import devLang from './dev-lang.json';
```

2023-09-28 11:16 UTC, barshathakuri commented on app/views/ProjectEdit/index.tsx
> +                                        title="Get sharable link for other users"
```suggestion
                                        title="Get shareable link for other users"
```

2023-09-28 11:16 UTC, barshathakuri commented on app/views/PublicReportView/index.tsx
> +    gql,
```suggestion
} from '@togglecorp/fujs';
import {
    useQuery,
    gql,
```

2023-09-28 11:16 UTC, barshathakuri commented on app/views/ReportEdit/index.tsx
> +import styles from './styles.css';
```suggestion
import { ContentDataFileMap } from '#components/report/utils';

import styles from './styles.css';
```

2023-10-31 10:02 UTC, puranban submitted a review, later dismissed

2023-11-08 08:22 UTC, subinasr approved these changes

2023-11-08 08:28 UTC, merged