Feature/update analysis module UI
the-deep/client pull request #2767
Opened 2023-09-26 11:03 UTC by AdityaKhatri

## Changes

* Update analysis module UI

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2023-09-27 06:54 UTC, subinasr approved these changes

2023-09-27 07:06 UTC, puranban commented on app/views/PillarAnalysis/SourceEntryItem/styles.css
> +    box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;
use predefined css variables to make UI consistent.

2023-09-27 07:08 UTC, puranban commented on app/views/AnalyticalFramework/schema.ts
remove unused variable

2023-09-27 07:08 UTC, puranban requested changes
`yarn typecheck && yarn lint`

2023-10-02 05:17 UTC, puranban approved these changes

2023-10-02 05:18 UTC, merged