Change to graphql query to list assignment
the-deep/client pull request #2870
Opened 2024-03-29 11:20 UTC by puranban

## Changes

* Change assignment list api from rest to graphql node

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2024-04-08 06:39 UTC, subinasr requested changes

2024-04-08 06:39 UTC, subinasr commented on app/views/Home/Assignment/AssignmentItem/index.tsx
> +type Assignment = NonNullable<NonNullable<GetAssignmentsQuery['assignment']>['results']>[number];
Let's import this type from Assignment as it has already been created there.

2024-04-08 06:39 UTC, subinasr commented on app/views/Home/Assignment/AssignmentItem/index.tsx
>                      // NOTE: Replace this later to clientId
We can remove this now.

2024-04-08 06:39 UTC, subinasr commented on app/views/Home/Assignment/index.tsx
> +                }
Is this necessary? I think the alert above handles this situation as well?

2024-04-08 06:39 UTC, subinasr commented on app/views/Home/Assignment/index.tsx
> +                }
same here

2024-04-08 06:39 UTC, subinasr commented on app/views/Home/Assignment/index.tsx
> +                        'Successfully mark all as read.',
```suggestion
                        'Successfully marked all as read.',
```

2024-04-08 06:39 UTC, subinasr commented on app/views/Home/Assignment/index.tsx
> +                        'Successfully mark as read.',
```suggestion
                        'Successfully marked as read.',
```

2024-04-09 04:27 UTC, puranban commented on app/views/Home/Assignment/AssignmentItem/index.tsx
>                      // NOTE: Replace this later to clientId
we cannot remove `leadId` because to edit the entry we need `leadId` as configured on the route.
so for now we can remove `projectId`.

2024-04-09 04:37 UTC, subinasr commented on app/views/Home/Assignment/AssignmentItem/index.tsx
>                      // NOTE: Replace this later to clientId
I meant the 'NOTE'.

2024-04-09 04:56 UTC, puranban commented on app/views/Home/Assignment/AssignmentItem/index.tsx
> +type Assignment = NonNullable<NonNullable<GetAssignmentsQuery['assignment']>['results']>[number];
The types returned from the query and Assignment are different which throw type error.

2024-04-09 08:04 UTC, subinasr requested changes

2024-04-09 08:04 UTC, subinasr commented on app/views/Home/Assignment/AssignmentItem/index.tsx
> +type Assignment = NonNullable<NonNullable<GetAssignmentsQuery['assignment']>['results']>[number];
Aren't we using the same type to create this 'Assignment' anyway?

2024-04-09 10:42 UTC, subinasr approved these changes

2024-04-10 04:38 UTC, shreeyash07 approved these changes

2024-04-10 04:39 UTC, merged