Implement graphql queries to fetch project roles
the-deep/client pull request #2885
Opened 2024-04-03 08:43 UTC by shreeyash07

- Addresses #2873 
- Depends on https://github.com/the-deep/server/pull/1461

## Changes

Replaced rest api with graphql in project roles options

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:
- [ ] permission checks
- [ ] translations

2024-04-05 06:22 UTC, AdityaKhatri requested changes

2024-04-05 06:22 UTC, AdityaKhatri commented on app/views/ProjectEdit/Users/UserGroupList/AddUserGroupModal/index.tsx
> -    ]);
This is still required.

2024-04-10 06:07 UTC, subinasr commented
@shreeyash07 The query has been updated from server side. Can you reflect those changes?

2024-04-24 05:39 UTC, AdityaKhatri approved these changes

2024-04-25 09:13 UTC, merged