temp
the-deep/client pull request #2951
Opened 2024-05-27 08:26 UTC by AdityaKhatri

- Addresses XXX
- Depends on XXX

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] build works
- [ ] eslint issues
- [ ] typescript issues
- [ ] codegen errors
- [ ] `console.log` meant for debugging
- [ ] typos
- [ ] unwanted comments
- [ ] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2024-08-08 09:16 UTC, shreeyash07 approved these changes

2024-08-12 08:19 UTC, subinasr requested changes

2024-08-12 08:19 UTC, subinasr commented on app/views/AnalyticalFramework/index.tsx
> +                return possibleAssociations?.some((ass) => {
Appropriate naming please.

2024-08-14 04:41 UTC, subinasr approved these changes
Tested, it works!

2024-08-21 08:37 UTC, merged