Add/analysis overview query
the-deep/client pull request #2970
Opened 2024-07-18 09:26 UTC by barshathakuri

- Addresses XXX
- Depends on XXX

## Changes

* Detailed list or prose of changes
* Breaking changes
* Changes to configurations

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [ ] permission checks
- [ ] translations

2024-07-18 10:25 UTC, AdityaKhatri requested changes

2024-07-18 10:25 UTC, AdityaKhatri commented on app/views/AnalysisDashboard/Analysis/AnalysisCloneModal/index.tsx
> +    /*
yo block nai hatauda huncha

2024-07-18 10:25 UTC, AdityaKhatri commented on app/views/AnalysisDashboard/Analysis/AnalysisCloneModal/index.tsx
> +import { useLazyRequest } from '#base/utils/restRequest';
TODO chodi rakha na, remove garna cha bhanera tha huncha

2024-07-18 10:25 UTC, AdityaKhatri commented on app/views/AnalysisDashboard/Analysis/AnalysisPillar/index.tsx
> +        onDelete(Number(pillarId));
Leave a TODO here as well

2024-07-18 10:25 UTC, AdityaKhatri commented on app/views/AnalysisDashboard/Analysis/AnalysisPillar/index.tsx
> -    const disabled = pendingPillarDelete;
We need this, don't we?

2024-07-18 10:25 UTC, AdityaKhatri commented on app/views/AnalysisDashboard/Analysis/PillarList/index.tsx
> -            pendingPillarDelete: pendingPillarDelete && data.id === deletePillarId,
Are we moving this inside?

2024-07-18 10:25 UTC, AdityaKhatri commented on app/views/AnalysisDashboard/Analysis/index.tsx
> +                heading={_ts('analysis', 'pillarAnalysisCount', { count: pillars?.length })}
Lets remove _ts and replace this directly with a text.

2024-07-18 10:25 UTC, AdityaKhatri commented on app/views/AnalysisDashboard/index.tsx
> +const timelineKeySelector = (d: TimelineData): string => d.key;
why replace the d?

2024-07-18 10:25 UTC, AdityaKhatri commented on app/views/AnalysisDashboard/index.tsx
> +    const analysisRendererParams = useCallback((id: string, data: AnalysisSummaryType) => ({
Add return time in renderer params for better typecheck

2024-08-30 08:34 UTC, AdityaKhatri requested changes

2024-08-30 08:34 UTC, AdityaKhatri commented on app/views/AnalysisDashboard/index.tsx
> -    const handleAnalysisEditClick = useCallback((analysisId: number | undefined) => {
Please do not undo this

2024-08-30 08:34 UTC, AdityaKhatri commented on app/views/AnalysisDashboard/index.tsx
> +    analysisId: string;
why? Please no

2024-11-07 05:11 UTC, shreeyash07 approved these changes

2024-11-22 04:19 UTC, merged