Retrigger Geo areas in Project edit page
the-deep/client pull request #3006
Opened 2024-12-03 10:55 UTC by shreeyash07

- Addresses #3005
- Depends on [fix/geo-area-failure-status-trigger](https://github.com/the-deep/server/pull/1537)

## Changes

* Add retrigger mutation in Region card
* Add retrigger button in region card
* Add polling for the refetchRegion due to background operation
* Add disable condition for publish area button

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR contains valid:

- [x] permission checks
- [x] translations

2024-12-04 10:42 UTC, AdityaKhatri requested changes

2024-12-04 10:42 UTC, AdityaKhatri commented on app/views/ProjectEdit/GeoAreas/RegionCard/AddAdminLevelPane/AddAdminLevelForm/index.tsx
> +    onRegionPublishSuccess: () => void;
Rename this appropriately

2024-12-04 10:42 UTC, AdityaKhatri commented on app/views/ProjectEdit/GeoAreas/RegionCard/index.tsx
> +                    onRegionPublishSuccess();
rename this approriately

2024-12-04 10:42 UTC, AdityaKhatri commented on app/views/ProjectEdit/GeoAreas/RegionCard/index.tsx
> +            {region.status === 'FAILED' && (
Check if the region is already published. If the region is already published this check is not necessary as the user won't/shouldn't be able to retrigger.

2024-12-04 10:42 UTC, AdityaKhatri commented on app/views/ProjectEdit/GeoAreas/RegionCard/index.tsx
> +                    {region.status === 'FAILED' && (
Check if the region is already published. If the region is already published this check is not necessary as the user won't/shouldn't be able to retrigger.

2024-12-05 04:48 UTC, AdityaKhatri approved these changes

2024-12-05 08:07 UTC, subinasr approved these changes

2024-12-05 10:58 UTC, merged