Feature/export leads
the-deep/client pull request #828
Opened 2019-07-09 18:10 UTC by AdityaKhatri

2019-07-10 04:51 UTC, tnagorra commented on src/redux/selectors/siloDomainData/addLeads.js
> +    leads => leads.map(leadAccessor.getServerId),
Don't we need to filter `null` or `undefined` values?

2019-07-10 04:53 UTC, tnagorra commented on src/views/Leads/ActionButtons/index.js
> +    getId = memoize(row => [row.id]);
We can still name this method: `getSomethingIds`

2019-07-10 04:53 UTC, tnagorra commented on src/views/Leads/ActionButtons/index.js
> +    getId = memoize(row => [row.id]);
`getLeadIds`

2019-07-10 04:54 UTC, tnagorra commented on src/views/Leads/GridItem/index.js
> +    getId = memoize(row => [row.id]);
The function name could be more informative.

2019-07-10 04:55 UTC, tnagorra requested changes
Code looks almost okay!

2019-07-10 08:12 UTC, thenav56 commented on src/components/general/LeadCopyModal/index.js
> +                    projectsCount: projects.count,
`.count` Is this new in JS?

2019-07-12 04:54 UTC, tnagorra commented on src/components/general/LeadCopyModal/index.js
> +@RequestCoordinator
We generally do not need request coordinator in a Modal.

2019-07-12 05:50 UTC, tnagorra commented on src/redux/selectors/siloDomainData/addLeads.js
> +    leads => leads.map(leadAccessor.getServerId).map(isDefined),
I think this should be filter instead of map

2019-07-12 06:39 UTC, merged