Remove required field for author in lead
the-deep/client pull request #909
Opened 2019-11-05 06:08 UTC by AdityaKhatri

* Change entries viz poll time from 20s to 3s
* Have consistent labeling in metadata tab (stakeholder header was larger than its adjacent field)

2019-11-06 08:33 UTC, samshara commented on src/views/Export/LeadsTable/index.js
> +    static leadKeyExtractor = d => d.id
add ; for consistency

2019-11-06 08:43 UTC, samshara reviewed
make requested changes

2019-11-06 08:46 UTC, AdityaKhatri commented on src/views/Export/LeadsTable/index.js
> +    static leadKeyExtractor = d => d.id
Okayy

2019-11-06 08:51 UTC, AdityaKhatri commented on src/views/Connector/index.js
> +            connectors
Lets use list to map

2019-11-06 15:27 UTC, tnagorra commented on src/views/Export/index.js
> +        leadsFromState.forEach((l) => {
Let's use Array.map, kind sir!

2019-11-06 15:28 UTC, tnagorra requested changes
Need to fix some problems first!

2019-11-07 05:39 UTC, tnagorra approved these changes

2019-11-07 05:44 UTC, tnagorra requested changes
Missed dsc/asc support for number in LeadGroups and Arys (RawTable)

2019-11-08 04:51 UTC, tnagorra approved these changes

2019-11-08 06:19 UTC, merged